// Generated by GraphQL Code Generator - DO NOT EDIT
package dev.yidafu.aqua.common.graphql.generated

data class Address(
    val city: kotlin.String,
    val cityCode: kotlin.String?,
    val createdAt: java.time.LocalDateTime,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val districtCode: kotlin.String?,
    val id: kotlin.Long,
    val isDefault: kotlin.Boolean,
    val latitude: kotlin.Float?,
    val longitude: kotlin.Float?,
    val phone: kotlin.String,
    val province: kotlin.String,
    val provinceCode: kotlin.String?,
    val receiverName: kotlin.String,
    val updatedAt: java.time.LocalDateTime,
    val userId: kotlin.Long
)

data class AddressInput(
    val city: kotlin.String,
    val cityCode: kotlin.String,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val districtCode: kotlin.String,
    val isDefault: kotlin.Boolean = false,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val phone: kotlin.String,
    val province: kotlin.String,
    val provinceCode: kotlin.String,
    val receiverName: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["cityCode"] as kotlin.String,
      args["detailAddress"] as kotlin.String,
      args["district"] as kotlin.String,
      args["districtCode"] as kotlin.String,
      args["isDefault"] as kotlin.Boolean? ?: false,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["phone"] as kotlin.String,
      args["province"] as kotlin.String,
      args["provinceCode"] as kotlin.String,
      args["receiverName"] as kotlin.String
  )
}

data class AddressPagePayload(
    val content: Iterable<Address>,
    val first: kotlin.Boolean,
    val last: kotlin.Boolean,
    val message: kotlin.String,
    val number: kotlin.Int,
    val size: kotlin.Int,
    val success: kotlin.Boolean,
    val totalElements: kotlin.Long,
    val totalPages: kotlin.Int
)

data class AddressPayload(
    val address: Address?,
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class AddressValidationInput(
    val city: kotlin.String,
    val cityCode: kotlin.String? = null,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val districtCode: kotlin.String? = null,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val province: kotlin.String,
    val provinceCode: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["cityCode"] as kotlin.String?,
      args["detailAddress"] as kotlin.String,
      args["district"] as kotlin.String,
      args["districtCode"] as kotlin.String?,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["province"] as kotlin.String,
      args["provinceCode"] as kotlin.String?
  )
}

data class AddressValidationPayload(
    val coordinatesValid: kotlin.Boolean,
    val errors: Iterable<kotlin.String>,
    val isDuplicate: kotlin.Boolean,
    val isValid: kotlin.Boolean,
    val message: kotlin.String,
    val normalizedAddress: NormalizedAddress?,
    val success: kotlin.Boolean
)

data class Admin(
    val createdAt: java.time.LocalDateTime,
    val id: kotlin.Long,
    val lastLoginAt: java.time.LocalDateTime?,
    val phone: kotlin.String?,
    val realName: kotlin.String?,
    val role: kotlin.String,
    val updatedAt: java.time.LocalDateTime,
    val username: kotlin.String
)

data class AuthPayload(
    val accessToken: kotlin.String,
    val refreshToken: kotlin.String,
    val user: User
)

data class BooleanPayload(
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class CreateAddressInput(
    val city: kotlin.String,
    val cityCode: kotlin.String? = null,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val districtCode: kotlin.String? = null,
    val isDefault: kotlin.Boolean? = null,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val province: kotlin.String,
    val provinceCode: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["cityCode"] as kotlin.String?,
      args["detailAddress"] as kotlin.String,
      args["district"] as kotlin.String,
      args["districtCode"] as kotlin.String?,
      args["isDefault"] as kotlin.Boolean?,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["province"] as kotlin.String,
      args["provinceCode"] as kotlin.String?
  )
}

data class CreateDeliveryAddressInput(
    val city: kotlin.String,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val province: kotlin.String,
    val receiverName: kotlin.String,
    val receiverPhone: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["detailAddress"] as kotlin.String,
      args["district"] as kotlin.String,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["province"] as kotlin.String,
      args["receiverName"] as kotlin.String,
      args["receiverPhone"] as kotlin.String
  )
}

data class CreateDeliveryAreaInput(
    val city: kotlin.String,
    val district: kotlin.String,
    val enabled: kotlin.Boolean? = null,
    val name: kotlin.String,
    val province: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["district"] as kotlin.String,
      args["enabled"] as kotlin.Boolean?,
      args["name"] as kotlin.String,
      args["province"] as kotlin.String
  )
}

data class CreateDeliveryWorkerInput(
    val avatarUrl: kotlin.String? = null,
    val coordinates: kotlin.String? = null,
    val currentLocation: kotlin.String? = null,
    val earning: java.math.BigDecimal? = null,
    val isAvailable: kotlin.Boolean? = null,
    val name: kotlin.String,
    val phone: kotlin.String,
    val rating: java.math.BigDecimal? = null,
    val wechatOpenId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["avatarUrl"] as kotlin.String?,
      args["coordinates"] as kotlin.String?,
      args["currentLocation"] as kotlin.String?,
      args["earning"] as java.math.BigDecimal?,
      args["isAvailable"] as kotlin.Boolean?,
      args["name"] as kotlin.String,
      args["phone"] as kotlin.String,
      args["rating"] as java.math.BigDecimal?,
      args["wechatOpenId"] as kotlin.String
  )
}

data class CreateManualRefundInput(
    val adminNote: kotlin.String? = null,
    val amount: java.math.BigDecimal,
    val orderId: kotlin.Long,
    val originalTransactionId: kotlin.String,
    val reason: kotlin.String,
    val userId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["adminNote"] as kotlin.String?,
      args["amount"] as java.math.BigDecimal,
      args["orderId"] as kotlin.Long,
      args["originalTransactionId"] as kotlin.String,
      args["reason"] as kotlin.String,
      args["userId"] as kotlin.Long
  )
}

data class CreateOrderInput(
    val addressId: kotlin.Long,
    val productId: kotlin.Long,
    val quantity: kotlin.Int
) {
  constructor(args: Map<String, Any>) : this(
      args["addressId"] as kotlin.Long,
      args["productId"] as kotlin.Long,
      args["quantity"] as kotlin.Int
  )
}

data class CreateProductInput(
    val coverImageUrl: kotlin.String,
    val description: kotlin.String? = null,
    val detailImages: kotlin.String? = null,
    val name: kotlin.String,
    val price: java.math.BigDecimal,
    val stock: kotlin.Int
) {
  constructor(args: Map<String, Any>) : this(
      args["coverImageUrl"] as kotlin.String,
      args["description"] as kotlin.String?,
      args["detailImages"] as kotlin.String?,
      args["name"] as kotlin.String,
      args["price"] as java.math.BigDecimal,
      args["stock"] as kotlin.Int
  )
}

data class CreateRegionInput(
    val code: kotlin.String,
    val level: kotlin.Int,
    val name: kotlin.String,
    val parentCode: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["code"] as kotlin.String,
      args["level"] as kotlin.Int,
      args["name"] as kotlin.String,
      args["parentCode"] as kotlin.String?
  )
}

data class CreateReviewRequestInput(
    val comment: kotlin.String? = null,
    val deliveryWorkerId: kotlin.Long,
    val isAnonymous: kotlin.Boolean? = null,
    val orderId: kotlin.Long,
    val rating: kotlin.Int
) {
  constructor(args: Map<String, Any>) : this(
      args["comment"] as kotlin.String?,
      args["deliveryWorkerId"] as kotlin.Long,
      args["isAnonymous"] as kotlin.Boolean?,
      args["orderId"] as kotlin.Long,
      args["rating"] as kotlin.Int
  )
}

data class CreateWechatPaymentInput(
    val amount: java.math.BigDecimal,
    val description: kotlin.String,
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["amount"] as java.math.BigDecimal,
      args["description"] as kotlin.String,
      args["orderId"] as kotlin.Long
  )
}

data class DailyPaymentStats(
    val averageTransactionAmount: java.math.BigDecimal,
    val date: kotlin.String,
    val failedTransactions: kotlin.Long,
    val paymentMethodBreakdown: Iterable<PaymentMethodStats>,
    val peakHour: kotlin.Int,
    val refundCount: kotlin.Long,
    val refundedAmount: java.math.BigDecimal,
    val successfulTransactions: kotlin.Long,
    val totalAmount: java.math.BigDecimal,
    val totalTransactions: kotlin.Long
)

data class DailyStatistic(
    val date: kotlin.String,
    val orderCount: kotlin.Int,
    val revenue: java.math.BigDecimal
)

data class DateRange(
    val endDate: java.time.LocalDateTime,
    val startDate: java.time.LocalDateTime
)

data class DateRangeInput(
    val endDate: java.time.LocalDateTime,
    val startDate: java.time.LocalDateTime
) {
  constructor(args: Map<String, Any>) : this(
      args["endDate"] as java.time.LocalDateTime,
      args["startDate"] as java.time.LocalDateTime
  )
}

data class DeliveryAddress(
    val city: kotlin.String,
    val createdAt: java.time.LocalDateTime,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val id: kotlin.Long,
    val latitude: kotlin.Float?,
    val longitude: kotlin.Float?,
    val province: kotlin.String,
    val receiverName: kotlin.String,
    val receiverPhone: kotlin.String,
    val updatedAt: java.time.LocalDateTime,
    val userId: kotlin.Long
)

data class DeliveryArea(
    val city: kotlin.String,
    val district: kotlin.String,
    val enabled: kotlin.Boolean,
    val id: kotlin.Long,
    val name: kotlin.String,
    val province: kotlin.String
)

data class DeliveryWorker(
    val avatarUrl: kotlin.String?,
    val averageRating: java.math.BigDecimal?,
    val completedOrders: kotlin.Int,
    val coordinates: kotlin.String?,
    val createdAt: java.time.LocalDateTime,
    val currentLocation: kotlin.String?,
    val earning: java.math.BigDecimal?,
    val id: kotlin.Long,
    val isAvailable: kotlin.Boolean,
    val name: kotlin.String,
    val phone: kotlin.String,
    val rating: java.math.BigDecimal?,
    val status: WorkerStatus,
    val totalOrders: kotlin.Int,
    val updatedAt: java.time.LocalDateTime,
    val userId: kotlin.Long,
    val wechatOpenId: kotlin.String
)

data class DeliveryWorkerRankingResponse(
    val averageRating: java.math.BigDecimal,
    val positiveRatingPercentage: kotlin.Float,
    val totalReviews: kotlin.Long,
    val workerId: kotlin.Long,
    val workerName: kotlin.String?
)

data class DeliveryWorkerStatistics(
    val averageRating: java.math.BigDecimal,
    val deliveryWorkerId: kotlin.Long,
    val fiveStarReviews: kotlin.Long,
    val fourStarReviews: kotlin.Long,
    val oneStarReviews: kotlin.Long,
    val threeStarReviews: kotlin.Long,
    val totalReviews: kotlin.Long,
    val twoStarReviews: kotlin.Long
)

data class DeliveryWorkerStatisticsResponse(
    val averageRating: java.math.BigDecimal,
    val deliveryWorkerId: kotlin.Long,
    val fiveStarReviews: kotlin.Long,
    val fourStarReviews: kotlin.Long,
    val lastUpdated: java.time.LocalDateTime,
    val oneStarReviews: kotlin.Long,
    val ratingDistribution: kotlin.collections.Map<String, Any>,
    val threeStarReviews: kotlin.Long,
    val totalReviews: kotlin.Long,
    val twoStarReviews: kotlin.Long,
    val workerName: kotlin.String?
)

data class DistancePayload(
    val distanceKm: kotlin.Float?,
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class ExportTransactionsInput(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null,
    val format: kotlin.String = """CSV""".trimIndent(),
    val includeMetadata: kotlin.Boolean = false,
    val maxAmount: java.math.BigDecimal? = null,
    val minAmount: java.math.BigDecimal? = null,
    val paymentMethod: PaymentMethod? = null,
    val status: PaymentStatus? = null,
    val userId: kotlin.Long? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?,
      args["format"] as kotlin.String? ?: """CSV""".trimIndent(),
      args["includeMetadata"] as kotlin.Boolean? ?: false,
      args["maxAmount"] as java.math.BigDecimal?,
      args["minAmount"] as java.math.BigDecimal?,
      args["paymentMethod"] as PaymentMethod?,
      args["status"] as PaymentStatus?,
      args["userId"] as kotlin.Long?
  )
}

data class GeocodeInput(
    val city: kotlin.String,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val province: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["detailAddress"] as kotlin.String,
      args["district"] as kotlin.String,
      args["province"] as kotlin.String
  )
}

data class GeocodePayload(
    val latitude: kotlin.Float?,
    val longitude: kotlin.Float?,
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class MonthlyStatistic(
    val month: kotlin.Int,
    val monthName: kotlin.String,
    val orderCount: kotlin.Int,
    val revenue: java.math.BigDecimal,
    val year: kotlin.Int
)

data class MutationCancelOrderArgs(
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long
  )
}
data class MutationCreateAddressArgs(
    val input: AddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      AddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateAddressEnhancedArgs(
    val input: CreateAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateAddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateDeliveryAddressArgs(
    val input: CreateDeliveryAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateDeliveryAddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateDeliveryAreaArgs(
    val input: CreateDeliveryAreaInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateDeliveryAreaInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateDeliveryWorkerArgs(
    val input: CreateDeliveryWorkerInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateDeliveryWorkerInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateManualRefundArgs(
    val input: CreateManualRefundInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateManualRefundInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateOrderArgs(
    val input: CreateOrderInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateOrderInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateProductArgs(
    val input: CreateProductInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateProductInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateRegionArgs(
    val input: CreateRegionInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateRegionInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateReviewArgs(
    val input: CreateReviewRequestInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateReviewRequestInput(args["input"] as Map<String, Any>)
  )
}
data class MutationCreateWechatPaymentArgs(
    val input: CreateWechatPaymentInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      CreateWechatPaymentInput(args["input"] as Map<String, Any>)
  )
}
data class MutationDecreaseStockArgs(
    val productId: kotlin.Long,
    val quantity: kotlin.Int
) {
  constructor(args: Map<String, Any>) : this(
      args["productId"] as kotlin.Long,
      args["quantity"] as kotlin.Int
  )
}
data class MutationDeleteAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationDeleteAddressEnhancedArgs(
    val addressId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["addressId"] as kotlin.Long
  )
}
data class MutationDeleteDeliveryAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationDeleteDeliveryAreaArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationDeleteDeliveryWorkerArgs(
    val workerId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["workerId"] as kotlin.Long
  )
}
data class MutationDeleteProductArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationDeleteRegionArgs(
    val code: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["code"] as kotlin.String
  )
}
data class MutationExportTransactionsArgs(
    val input: ExportTransactionsInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      ExportTransactionsInput(args["input"] as Map<String, Any>)
  )
}
data class MutationForceCompletePaymentArgs(
    val adminNote: kotlin.String,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["adminNote"] as kotlin.String,
      args["transactionId"] as kotlin.String
  )
}
data class MutationForceRefundArgs(
    val adminNote: kotlin.String,
    val amount: java.math.BigDecimal,
    val reason: kotlin.String,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["adminNote"] as kotlin.String,
      args["amount"] as java.math.BigDecimal,
      args["reason"] as kotlin.String,
      args["transactionId"] as kotlin.String
  )
}
data class MutationFreezeSuspiciousTransactionArgs(
    val reason: kotlin.String,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["reason"] as kotlin.String,
      args["transactionId"] as kotlin.String
  )
}
data class MutationGeocodeAddressArgs(
    val address: GeocodeInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      GeocodeInput(args["address"] as Map<String, Any>)
  )
}
data class MutationHandleWechatCallbackArgs(
    val input: WechatCallbackInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      WechatCallbackInput(args["input"] as Map<String, Any>)
  )
}
data class MutationIncreaseStockArgs(
    val productId: kotlin.Long,
    val quantity: kotlin.Int
) {
  constructor(args: Map<String, Any>) : this(
      args["productId"] as kotlin.Long,
      args["quantity"] as kotlin.Int
  )
}
data class MutationProcessRefundArgs(
    val input: ProcessRefundInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      ProcessRefundInput(args["input"] as Map<String, Any>)
  )
}
data class MutationProcessSuspiciousTransactionArgs(
    val input: ProcessSuspiciousTransactionInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      ProcessSuspiciousTransactionInput(args["input"] as Map<String, Any>)
  )
}
data class MutationRefreshTokenArgs(
    val input: RefreshTokenInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      RefreshTokenInput(args["input"] as Map<String, Any>)
  )
}
data class MutationRefundArgs(
    val input: RefundInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      RefundInput(args["input"] as Map<String, Any>)
  )
}
data class MutationRequestRefundArgs(
    val input: RequestRefundInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      RequestRefundInput(args["input"] as Map<String, Any>)
  )
}
data class MutationReverseGeocodeArgs(
    val latitude: kotlin.Float,
    val longitude: kotlin.Float
) {
  constructor(args: Map<String, Any>) : this(
      args["latitude"] as kotlin.Float,
      args["longitude"] as kotlin.Float
  )
}
data class MutationSetDefaultAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationSetDefaultAddressEnhancedArgs(
    val addressId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["addressId"] as kotlin.Long
  )
}
data class MutationSetDefaultDeliveryAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class MutationUpdateAddressArgs(
    val id: kotlin.Long,
    val input: UpdateAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long,
      UpdateAddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateAddressEnhancedArgs(
    val addressId: kotlin.Long,
    val input: UpdateAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["addressId"] as kotlin.Long,
      UpdateAddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateDeliveryAddressArgs(
    val id: kotlin.Long,
    val input: UpdateDeliveryAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long,
      UpdateDeliveryAddressInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateDeliveryAreaArgs(
    val id: kotlin.Long,
    val input: CreateDeliveryAreaInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long,
      CreateDeliveryAreaInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateDeliveryWorkerArgs(
    val input: UpdateDeliveryWorkerInput,
    val workerId: kotlin.Long
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      UpdateDeliveryWorkerInput(args["input"] as Map<String, Any>),
      args["workerId"] as kotlin.Long
  )
}
data class MutationUpdateOrderStatusArgs(
    val orderId: kotlin.Long,
    val status: OrderStatus
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long,
      args["status"] as OrderStatus
  )
}
data class MutationUpdateProductArgs(
    val id: kotlin.Long,
    val input: UpdateProductInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long,
      UpdateProductInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateProfileArgs(
    val input: UpdateProfileInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      UpdateProfileInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateRegionArgs(
    val code: kotlin.String,
    val input: UpdateRegionInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      args["code"] as kotlin.String,
      UpdateRegionInput(args["input"] as Map<String, Any>)
  )
}
data class MutationUpdateTransactionArgs(
    val input: UpdateTransactionInput,
    val transactionId: kotlin.String
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      UpdateTransactionInput(args["input"] as Map<String, Any>),
      args["transactionId"] as kotlin.String
  )
}
data class MutationUpdateTransactionNoteArgs(
    val note: kotlin.String,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["note"] as kotlin.String,
      args["transactionId"] as kotlin.String
  )
}
data class MutationUpdateWorkerStatusArgs(
    val status: WorkerStatus,
    val workerId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["status"] as WorkerStatus,
      args["workerId"] as kotlin.Long
  )
}
data class MutationValidateAddressArgs(
    val input: AddressValidationInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      AddressValidationInput(args["input"] as Map<String, Any>)
  )
}
data class MutationWechatLoginArgs(
    val input: WechatLoginInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      WechatLoginInput(args["input"] as Map<String, Any>)
  )
}
data class Mutation(
    val cancelOrder: Order,
    val createAddress: Address,
    val createAddressEnhanced: AddressPayload,
    val createDeliveryAddress: DeliveryAddress,
    val createDeliveryArea: DeliveryArea,
    val createDeliveryWorker: DeliveryWorker,
    val createManualRefund: RefundRequest,
    val createOrder: Order,
    val createProduct: Product,
    val createRegion: Region,
    val createReview: Review,
    val createWechatPayment: PaymentData,
    val decreaseStock: kotlin.Boolean,
    val deleteAddress: kotlin.Boolean,
    val deleteAddressEnhanced: BooleanPayload,
    val deleteDeliveryAddress: kotlin.Boolean,
    val deleteDeliveryArea: kotlin.Boolean,
    val deleteDeliveryWorker: kotlin.Boolean,
    val deleteProduct: kotlin.Boolean,
    val deleteRegion: kotlin.Boolean,
    val exportTransactions: kotlin.String,
    val forceCompletePayment: kotlin.Boolean,
    val forceRefund: kotlin.Boolean,
    val freezeSuspiciousTransaction: kotlin.Boolean,
    val geocodeAddress: GeocodePayload,
    val handleWechatCallback: kotlin.String,
    val increaseStock: kotlin.String,
    val logout: kotlin.Boolean,
    val processRefund: RefundRequest,
    val processSuspiciousTransaction: SuspiciousTransaction,
    val refreshToken: WeChatTokenResponse,
    val refund: kotlin.Boolean,
    val requestRefund: RefundRequest,
    val reverseGeocode: ReverseGeocodePayload,
    val setDefaultAddress: kotlin.Boolean,
    val setDefaultAddressEnhanced: BooleanPayload,
    val setDefaultDeliveryAddress: kotlin.Boolean,
    val updateAddress: Address,
    val updateAddressEnhanced: AddressPayload,
    val updateDeliveryAddress: DeliveryAddress,
    val updateDeliveryArea: DeliveryArea,
    val updateDeliveryWorker: DeliveryWorker,
    val updateOrderStatus: Order,
    val updateProduct: Product,
    val updateProfile: UserInfo,
    val updateRegion: Region,
    val updateTransaction: PaymentTransaction,
    val updateTransactionNote: kotlin.Boolean,
    val updateWorkerStatus: DeliveryWorker,
    val validateAddress: AddressValidationPayload,
    val wechatLogin: WeChatLoginResponse
)

data class NearbyAddressesPayload(
    val addresses: Iterable<Address>,
    val distanceMap: kotlin.collections.Map<String, Any>,
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class NormalizedAddress(
    val city: kotlin.String,
    val cityCode: kotlin.String?,
    val detailAddress: kotlin.String,
    val district: kotlin.String,
    val districtCode: kotlin.String?,
    val province: kotlin.String,
    val provinceCode: kotlin.String?
)

data class Order(
    val address: Address,
    val amount: java.math.BigDecimal,
    val completedAt: java.time.LocalDateTime?,
    val createdAt: java.time.LocalDateTime,
    val deliveryPhotos: Iterable<kotlin.String>?,
    val deliveryWorker: DeliveryWorker?,
    val id: kotlin.Long,
    val orderNumber: kotlin.String,
    val paymentMethod: kotlin.String?,
    val paymentTime: java.time.LocalDateTime?,
    val paymentTransactionId: kotlin.String?,
    val product: Product,
    val quantity: kotlin.Int,
    val status: OrderStatus,
    val updatedAt: java.time.LocalDateTime,
    val user: User
)

data class OrderPaymentInfo(
    val amount: java.math.BigDecimal,
    val createdAt: java.time.LocalDateTime,
    val orderId: kotlin.Long,
    val orderNumber: kotlin.String,
    val paidAt: java.time.LocalDateTime?,
    val paymentMethod: PaymentMethod,
    val refundAmount: java.math.BigDecimal?,
    val refundedAt: java.time.LocalDateTime?,
    val status: PaymentStatus,
    val transactionId: kotlin.String?
)

data class OrderReviewCheckResponse(
    val canReview: kotlin.Boolean,
    val hasReviewed: kotlin.Boolean,
    val review: Review?
)

data class OrderStatistics(
    val averageOrderValue: java.math.BigDecimal,
    val dateRange: DateRange,
    val totalOrders: kotlin.Int,
    val totalRevenue: java.math.BigDecimal
)

enum class OrderStatus(val label: String) {
      Cancelled("CANCELLED"),
      Confirmed("CONFIRMED"),
      Delivered("DELIVERED"),
      OutForDelivery("OUT_FOR_DELIVERY"),
      Pending("PENDING"),
      Preparing("PREPARING"),
      ReadyForDelivery("READY_FOR_DELIVERY"),
      Refunded("REFUNDED");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): OrderStatus? {
      return values().find { it.label == label }
    }
  }
}

data class PaymentData(
    val appId: kotlin.String,
    val codeUrl: kotlin.String,
    val nonceStr: kotlin.String,
    val outTradeNo: kotlin.String,
    val packageValue: kotlin.String,
    val paySign: kotlin.String,
    val signType: kotlin.String,
    val timeStamp: kotlin.String
)

enum class PaymentMethod(val label: String) {
      Alipay("ALIPAY"),
      CashOnDelivery("CASH_ON_DELIVERY"),
      WechatPay("WECHAT_PAY");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): PaymentMethod? {
      return values().find { it.label == label }
    }
  }
}

data class PaymentMethodStats(
    val averageAmount: java.math.BigDecimal,
    val failureCount: kotlin.Long,
    val paymentMethod: PaymentMethod,
    val refundCount: kotlin.Long,
    val successCount: kotlin.Long,
    val successRate: kotlin.Float,
    val totalAmount: java.math.BigDecimal,
    val transactionCount: kotlin.Long
)

data class PaymentPeriodStats(
    val averageTransactionAmount: java.math.BigDecimal,
    val failedTransactions: kotlin.Long,
    val paymentMethodBreakdown: Iterable<PaymentMethodStats>,
    val period: kotlin.String,
    val successfulTransactions: kotlin.Long,
    val totalAmount: java.math.BigDecimal,
    val totalTransactions: kotlin.Long
)

data class PaymentStatistics(
    val averageTransactionAmount: java.math.BigDecimal,
    val dailyStats: Iterable<DailyPaymentStats>,
    val failedTransactions: kotlin.Long,
    val refundCount: kotlin.Long,
    val refundedAmount: java.math.BigDecimal,
    val successfulTransactions: kotlin.Long,
    val totalAmount: java.math.BigDecimal,
    val totalTransactions: kotlin.Long
)

enum class PaymentStatus(val label: String) {
      Failed("FAILED"),
      Processing("PROCESSING"),
      Refunded("REFUNDED"),
      Success("SUCCESS");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): PaymentStatus? {
      return values().find { it.label == label }
    }
  }
}

data class PaymentStatusInfo(
    val amount: java.math.BigDecimal,
    val createdAt: java.time.LocalDateTime,
    val failureReason: kotlin.String?,
    val orderNumber: kotlin.String,
    val paidAt: java.time.LocalDateTime?,
    val refundAmount: java.math.BigDecimal?,
    val refundedAt: java.time.LocalDateTime?,
    val status: PaymentStatus,
    val transactionId: kotlin.String,
    val updatedAt: java.time.LocalDateTime
)

data class PaymentTransaction(
    val adminNote: kotlin.String?,
    val amount: java.math.BigDecimal,
    val completedAt: java.time.LocalDateTime?,
    val createdAt: java.time.LocalDateTime,
    val externalTransactionId: kotlin.String?,
    val failureReason: kotlin.String?,
    val gateway: kotlin.String,
    val id: kotlin.String,
    val metadata: kotlin.collections.Map<String, Any>?,
    val orderId: kotlin.Long,
    val paymentMethod: PaymentMethod,
    val status: PaymentStatus,
    val transactionId: kotlin.String?,
    val updatedAt: java.time.LocalDateTime,
    val userId: kotlin.Long
)

data class ProcessRefundInput(
    val action: RefundAction,
    val adminNote: kotlin.String? = null,
    val amount: java.math.BigDecimal,
    val orderId: kotlin.Long,
    val originalTransactionId: kotlin.String,
    val reason: kotlin.String,
    val refundRequestId: kotlin.String,
    val userId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["action"] as RefundAction,
      args["adminNote"] as kotlin.String?,
      args["amount"] as java.math.BigDecimal,
      args["orderId"] as kotlin.Long,
      args["originalTransactionId"] as kotlin.String,
      args["reason"] as kotlin.String,
      args["refundRequestId"] as kotlin.String,
      args["userId"] as kotlin.Long
  )
}

data class ProcessSuspiciousTransactionInput(
    val action: kotlin.String,
    val adminNote: kotlin.String? = null,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["action"] as kotlin.String,
      args["adminNote"] as kotlin.String?,
      args["transactionId"] as kotlin.String
  )
}

data class Product(
    val coverImageUrl: kotlin.String,
    val createdAt: java.time.LocalDateTime,
    val description: kotlin.String?,
    val detailImages: kotlin.String?,
    val id: kotlin.Long,
    val name: kotlin.String,
    val price: java.math.BigDecimal,
    val status: ProductStatus,
    val stock: kotlin.Int,
    val updatedAt: java.time.LocalDateTime
)

enum class ProductStatus(val label: String) {
      Offline("OFFLINE"),
      Online("ONLINE");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): ProductStatus? {
      return values().find { it.label == label }
    }
  }
}

data class QueryAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryAdminArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryCalculateDistanceArgs(
    val lat1: kotlin.Float,
    val lat2: kotlin.Float,
    val lng1: kotlin.Float,
    val lng2: kotlin.Float
) {
  constructor(args: Map<String, Any>) : this(
      args["lat1"] as kotlin.Float,
      args["lat2"] as kotlin.Float,
      args["lng1"] as kotlin.Float,
      args["lng2"] as kotlin.Float
  )
}
data class QueryCheckOrderReviewArgs(
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long
  )
}
data class QueryDailyPaymentStatisticsArgs(
    val dateFrom: java.time.LocalDateTime,
    val dateTo: java.time.LocalDateTime
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime,
      args["dateTo"] as java.time.LocalDateTime
  )
}
data class QueryDailyStatisticsArgs(
    val input: DateRangeInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      DateRangeInput(args["input"] as Map<String, Any>)
  )
}
data class QueryDeliveryAddressArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryDeliveryAreaArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryDeliveryWorkerArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryDeliveryWorkerPublicStatisticsArgs(
    val deliveryWorkerId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["deliveryWorkerId"] as kotlin.Long
  )
}
data class QueryDeliveryWorkerRankingArgs(
    val minReviews: kotlin.Int? = null,
    val page: kotlin.Int? = null,
    val size: kotlin.Int? = null,
    val sortBy: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["minReviews"] as kotlin.Int?,
      args["page"] as kotlin.Int?,
      args["size"] as kotlin.Int?,
      args["sortBy"] as kotlin.String?
  )
}
data class QueryDeliveryWorkerReviewsArgs(
    val deliveryWorkerId: kotlin.Long,
    val page: kotlin.Int? = null,
    val size: kotlin.Int? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["deliveryWorkerId"] as kotlin.Long,
      args["page"] as kotlin.Int?,
      args["size"] as kotlin.Int?
  )
}
data class QueryDeliveryWorkerStatisticsArgs(
    val deliveryWorkerId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["deliveryWorkerId"] as kotlin.Long
  )
}
data class QueryIsInServiceAreaArgs(
    val latitude: kotlin.Float,
    val longitude: kotlin.Float
) {
  constructor(args: Map<String, Any>) : this(
      args["latitude"] as kotlin.Float,
      args["longitude"] as kotlin.Float
  )
}
data class QueryMonthlyStatisticsArgs(
    val input: DateRangeInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      DateRangeInput(args["input"] as Map<String, Any>)
  )
}
data class QueryMyPaymentTransactionsArgs(
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20
) {
  constructor(args: Map<String, Any>) : this(
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20
  )
}
data class QueryMyRefundRequestsArgs(
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20
) {
  constructor(args: Map<String, Any>) : this(
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20
  )
}
data class QueryMyReviewsArgs(
    val page: kotlin.Int? = null,
    val size: kotlin.Int? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["page"] as kotlin.Int?,
      args["size"] as kotlin.Int?
  )
}
data class QueryNearbyAddressesArgs(
    val latitude: kotlin.Float,
    val longitude: kotlin.Float,
    val radiusKm: kotlin.Float? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["latitude"] as kotlin.Float,
      args["longitude"] as kotlin.Float,
      args["radiusKm"] as kotlin.Float?
  )
}
data class QueryOrderArgs(
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long
  )
}
data class QueryOrderByNumberArgs(
    val orderNumber: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["orderNumber"] as kotlin.String
  )
}
data class QueryOrderPaymentInfoArgs(
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long
  )
}
data class QueryOrderStatisticsArgs(
    val input: DateRangeInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      DateRangeInput(args["input"] as Map<String, Any>)
  )
}
data class QueryOrdersByStatusArgs(
    val status: OrderStatus
) {
  constructor(args: Map<String, Any>) : this(
      args["status"] as OrderStatus
  )
}
data class QueryOrdersByUserArgs(
    val userId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["userId"] as kotlin.Long
  )
}
data class QueryOrdersByUserAndStatusArgs(
    val status: OrderStatus,
    val userId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["status"] as OrderStatus,
      args["userId"] as kotlin.Long
  )
}
data class QueryPaymentMethodStatisticsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?
  )
}
data class QueryPaymentPeriodStatsArgs(
    val from: java.time.LocalDateTime,
    val to: java.time.LocalDateTime
) {
  constructor(args: Map<String, Any>) : this(
      args["from"] as java.time.LocalDateTime,
      args["to"] as java.time.LocalDateTime
  )
}
data class QueryPaymentStatisticsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?
  )
}
data class QueryPaymentStatusArgs(
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["transactionId"] as kotlin.String
  )
}
data class QueryPaymentTransactionArgs(
    val id: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.String
  )
}
data class QueryPaymentTransactionsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null,
    val maxAmount: java.math.BigDecimal? = null,
    val minAmount: java.math.BigDecimal? = null,
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20,
    val status: PaymentStatus? = null,
    val userId: kotlin.Long? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?,
      args["maxAmount"] as java.math.BigDecimal?,
      args["minAmount"] as java.math.BigDecimal?,
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20,
      args["status"] as PaymentStatus?,
      args["userId"] as kotlin.Long?
  )
}
data class QueryProductArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryRefundEligibilityArgs(
    val orderId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["orderId"] as kotlin.Long
  )
}
data class QueryRefundRequestArgs(
    val id: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.String
  )
}
data class QueryRefundRequestsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null,
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20,
    val status: RefundStatus? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?,
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20,
      args["status"] as RefundStatus?
  )
}
data class QueryRegionArgs(
    val code: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["code"] as kotlin.String
  )
}
data class QueryRegionByCoordinatesArgs(
    val latitude: kotlin.Float,
    val longitude: kotlin.Float
) {
  constructor(args: Map<String, Any>) : this(
      args["latitude"] as kotlin.Float,
      args["longitude"] as kotlin.Float
  )
}
data class QueryRegionsArgs(
    val level: kotlin.Int? = null,
    val parentCode: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["level"] as kotlin.Int?,
      args["parentCode"] as kotlin.String?
  )
}
data class QueryReviewsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null,
    val deliveryWorkerId: kotlin.Long? = null,
    val maxRating: kotlin.Int? = null,
    val minRating: kotlin.Int? = null,
    val page: kotlin.Int? = null,
    val size: kotlin.Int? = null,
    val userId: kotlin.Long? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?,
      args["deliveryWorkerId"] as kotlin.Long?,
      args["maxRating"] as kotlin.Int?,
      args["minRating"] as kotlin.Int?,
      args["page"] as kotlin.Int?,
      args["size"] as kotlin.Int?,
      args["userId"] as kotlin.Long?
  )
}
data class QuerySearchRegionsArgs(
    val keyword: kotlin.String,
    val level: kotlin.Int? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["keyword"] as kotlin.String,
      args["level"] as kotlin.Int?
  )
}
data class QuerySuspiciousTransactionsArgs(
    val dateFrom: java.time.LocalDateTime? = null,
    val dateTo: java.time.LocalDateTime? = null,
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20
) {
  constructor(args: Map<String, Any>) : this(
      args["dateFrom"] as java.time.LocalDateTime?,
      args["dateTo"] as java.time.LocalDateTime?,
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20
  )
}
data class QueryUserArgs(
    val id: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["id"] as kotlin.Long
  )
}
data class QueryUserAddressPageArgs(
    val direction: kotlin.String? = null,
    val page: kotlin.Int? = null,
    val size: kotlin.Int? = null,
    val sort: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["direction"] as kotlin.String?,
      args["page"] as kotlin.Int?,
      args["size"] as kotlin.Int?,
      args["sort"] as kotlin.String?
  )
}
data class QueryUserPaymentTransactionsArgs(
    val page: kotlin.Int? = 0,
    val size: kotlin.Int? = 20,
    val userId: kotlin.Long
) {
  constructor(args: Map<String, Any>) : this(
      args["page"] as kotlin.Int? ?: 0,
      args["size"] as kotlin.Int? ?: 20,
      args["userId"] as kotlin.Long
  )
}
data class QueryValidateAddressArgs(
    val input: ValidateAddressInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      ValidateAddressInput(args["input"] as Map<String, Any>)
  )
}
data class QueryWeeklyStatisticsArgs(
    val input: DateRangeInput
) {
  @Suppress("UNCHECKED_CAST")
  constructor(args: Map<String, Any>) : this(
      DateRangeInput(args["input"] as Map<String, Any>)
  )
}
data class Query(
    val activeProducts: Iterable<Product>,
    val address: Address?,
    val addresses: Iterable<Address>,
    val admin: Admin?,
    val admins: Iterable<Admin>,
    val calculateDistance: DistancePayload?,
    val checkOrderReview: OrderReviewCheckResponse,
    val dailyPaymentStatistics: Iterable<DailyPaymentStats>,
    val dailyStatistics: Iterable<DailyStatistic>,
    val defaultRegionHierarchy: RegionHierarchy?,
    val deliveryAddress: DeliveryAddress?,
    val deliveryAddresses: Iterable<DeliveryAddress>,
    val deliveryArea: DeliveryArea?,
    val deliveryAreas: Iterable<DeliveryArea>,
    val deliveryWorker: DeliveryWorker?,
    val deliveryWorkerPublicStatistics: Review,
    val deliveryWorkerRanking: Iterable<DeliveryWorkerRankingResponse>,
    val deliveryWorkerReviews: Iterable<Review>,
    val deliveryWorkerStatistics: DeliveryWorkerStatisticsResponse,
    val deliveryWorkers: Iterable<DeliveryWorker>,
    val enabledDeliveryAreas: Iterable<DeliveryArea>,
    val isInServiceArea: ServiceAreaPayload?,
    val me: UserInfo?,
    val monthlyStatistics: Iterable<MonthlyStatistic>,
    val myPaymentTransactions: Iterable<UserPaymentTransaction>,
    val myRefundRequests: Iterable<RefundRequest>,
    val myReviews: Iterable<Review>,
    val nearbyAddresses: NearbyAddressesPayload?,
    val onlineDeliveryWorkers: Iterable<DeliveryWorker>,
    val order: Order?,
    val orderByNumber: Order?,
    val orderPaymentInfo: OrderPaymentInfo,
    val orderStatistics: OrderStatistics,
    val ordersByStatus: Iterable<Order>,
    val ordersByUser: Iterable<Order>,
    val ordersByUserAndStatus: Iterable<Order>,
    val paymentMethodStatistics: Iterable<PaymentMethodStats>,
    val paymentPeriodStats: Iterable<PaymentPeriodStats>,
    val paymentStatistics: PaymentStatistics?,
    val paymentStatus: kotlin.String,
    val paymentTransaction: PaymentTransaction?,
    val paymentTransactions: Iterable<PaymentTransaction>,
    val product: Product?,
    val products: Iterable<Product>,
    val refundEligibility: RefundEligibility,
    val refundRequest: RefundRequest?,
    val refundRequests: Iterable<RefundRequest>,
    val region: Region?,
    val regionByCoordinates: RegionCoordinatesPayload?,
    val regions: Iterable<Region>,
    val reviews: Iterable<Review>,
    val searchRegions: Iterable<Region>,
    val suspiciousTransactions: Iterable<SuspiciousTransaction>,
    val user: User?,
    val userAddressPage: AddressPagePayload?,
    val userAddresses: Iterable<Address>,
    val userDefaultAddress: Address?,
    val userPaymentTransactions: Iterable<PaymentTransaction>,
    val validateAddress: kotlin.Boolean,
    val weeklyStatistics: Iterable<WeeklyStatistic>
)

data class RefreshTokenInput(
    val refreshToken: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["refreshToken"] as kotlin.String
  )
}

enum class RefundAction(val label: String) {
      Approve("APPROVE"),
      Reject("REJECT");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): RefundAction? {
      return values().find { it.label == label }
    }
  }
}

data class RefundEligibility(
    val deadline: java.time.LocalDateTime?,
    val eligible: kotlin.Boolean,
    val orderAmount: java.math.BigDecimal,
    val orderId: kotlin.Long,
    val paidAmount: java.math.BigDecimal,
    val refundPolicy: kotlin.String?,
    val refundReason: kotlin.String?,
    val refundableAmount: java.math.BigDecimal
)

data class RefundInput(
    val refundAmount: java.math.BigDecimal,
    val totalAmount: java.math.BigDecimal,
    val transactionId: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["refundAmount"] as java.math.BigDecimal,
      args["totalAmount"] as java.math.BigDecimal,
      args["transactionId"] as kotlin.String
  )
}

data class RefundRequest(
    val adminNote: kotlin.String?,
    val amount: java.math.BigDecimal,
    val id: kotlin.String,
    val orderId: kotlin.Long,
    val originalTransactionId: kotlin.String,
    val processedAt: java.time.LocalDateTime?,
    val processedBy: kotlin.Long?,
    val reason: kotlin.String,
    val requestedAt: java.time.LocalDateTime,
    val status: RefundStatus,
    val userId: kotlin.Long
)

enum class RefundStatus(val label: String) {
      Approved("APPROVED"),
      Completed("COMPLETED"),
      Failed("FAILED"),
      Pending("PENDING"),
      Rejected("REJECTED");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): RefundStatus? {
      return values().find { it.label == label }
    }
  }
}

data class Region(
    val code: kotlin.String,
    val createdAt: java.time.LocalDateTime,
    val id: kotlin.Long,
    val level: kotlin.Int,
    val name: kotlin.String,
    val parentCode: kotlin.String?,
    val updatedAt: java.time.LocalDateTime
)

data class RegionCoordinatesPayload(
    val message: kotlin.String,
    val region: Region?,
    val success: kotlin.Boolean
)

data class RegionHierarchy(
    val cities: Iterable<Region>,
    val city: Region,
    val district: Region,
    val districts: Iterable<Region>,
    val province: Region,
    val provinces: Iterable<Region>
)

data class RequestRefundInput(
    val amount: java.math.BigDecimal,
    val orderId: kotlin.Long,
    val outTradeNo: kotlin.String,
    val reason: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["amount"] as java.math.BigDecimal,
      args["orderId"] as kotlin.Long,
      args["outTradeNo"] as kotlin.String,
      args["reason"] as kotlin.String
  )
}

data class ReverseGeocodePayload(
    val city: kotlin.String?,
    val cityCode: kotlin.String?,
    val confidence: kotlin.Float?,
    val district: kotlin.String?,
    val districtCode: kotlin.String?,
    val formattedAddress: kotlin.String?,
    val message: kotlin.String,
    val province: kotlin.String?,
    val provinceCode: kotlin.String?,
    val street: kotlin.String?,
    val success: kotlin.Boolean
)

data class Review(
    val comment: kotlin.String?,
    val createdAt: java.time.LocalDateTime,
    val deliveryWorkerId: kotlin.Long,
    val deliveryWorkerName: kotlin.String?,
    val isAnonymous: kotlin.Boolean,
    val orderId: kotlin.Long,
    val rating: kotlin.Int,
    val reviewId: kotlin.Long,
    val userId: kotlin.Long?
)

data class ServiceAreaPayload(
    val inServiceArea: kotlin.Boolean,
    val message: kotlin.String,
    val success: kotlin.Boolean
)

data class SuspiciousTransaction(
    val adminNote: kotlin.String?,
    val amount: java.math.BigDecimal,
    val createdAt: java.time.LocalDateTime,
    val frozenAt: java.time.LocalDateTime?,
    val frozenBy: kotlin.Long?,
    val id: kotlin.String,
    val isFrozen: kotlin.Boolean,
    val metadata: kotlin.collections.Map<String, Any>?,
    val orderId: kotlin.Long,
    val paymentMethod: PaymentMethod,
    val riskScore: kotlin.Float,
    val status: PaymentStatus,
    val suspiciousReason: kotlin.String,
    val transactionId: kotlin.String?,
    val userId: kotlin.Long
)

data class UpdateAddressInput(
    val city: kotlin.String? = null,
    val cityCode: kotlin.String? = null,
    val detailAddress: kotlin.String? = null,
    val district: kotlin.String? = null,
    val districtCode: kotlin.String? = null,
    val isDefault: kotlin.Boolean? = null,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val phone: kotlin.String? = null,
    val province: kotlin.String? = null,
    val provinceCode: kotlin.String? = null,
    val receiverName: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String?,
      args["cityCode"] as kotlin.String?,
      args["detailAddress"] as kotlin.String?,
      args["district"] as kotlin.String?,
      args["districtCode"] as kotlin.String?,
      args["isDefault"] as kotlin.Boolean?,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["phone"] as kotlin.String?,
      args["province"] as kotlin.String?,
      args["provinceCode"] as kotlin.String?,
      args["receiverName"] as kotlin.String?
  )
}

data class UpdateDeliveryAddressInput(
    val city: kotlin.String? = null,
    val detailAddress: kotlin.String? = null,
    val district: kotlin.String? = null,
    val latitude: kotlin.Float? = null,
    val longitude: kotlin.Float? = null,
    val province: kotlin.String? = null,
    val receiverName: kotlin.String? = null,
    val receiverPhone: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String?,
      args["detailAddress"] as kotlin.String?,
      args["district"] as kotlin.String?,
      args["latitude"] as kotlin.Float?,
      args["longitude"] as kotlin.Float?,
      args["province"] as kotlin.String?,
      args["receiverName"] as kotlin.String?,
      args["receiverPhone"] as kotlin.String?
  )
}

data class UpdateDeliveryWorkerInput(
    val avatarUrl: kotlin.String? = null,
    val coordinates: kotlin.String? = null,
    val currentLocation: kotlin.String? = null,
    val earning: java.math.BigDecimal? = null,
    val isAvailable: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val phone: kotlin.String? = null,
    val rating: java.math.BigDecimal? = null,
    val wechatOpenId: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["avatarUrl"] as kotlin.String?,
      args["coordinates"] as kotlin.String?,
      args["currentLocation"] as kotlin.String?,
      args["earning"] as java.math.BigDecimal?,
      args["isAvailable"] as kotlin.Boolean?,
      args["name"] as kotlin.String?,
      args["phone"] as kotlin.String?,
      args["rating"] as java.math.BigDecimal?,
      args["wechatOpenId"] as kotlin.String?
  )
}

data class UpdateProductInput(
    val coverImageUrl: kotlin.String? = null,
    val description: kotlin.String? = null,
    val detailImages: kotlin.String? = null,
    val name: kotlin.String? = null,
    val price: java.math.BigDecimal? = null,
    val stock: kotlin.Int? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["coverImageUrl"] as kotlin.String?,
      args["description"] as kotlin.String?,
      args["detailImages"] as kotlin.String?,
      args["name"] as kotlin.String?,
      args["price"] as java.math.BigDecimal?,
      args["stock"] as kotlin.Int?
  )
}

data class UpdateProfileInput(
    val avatar: kotlin.String? = null,
    val nickname: kotlin.String? = null,
    val phone: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["avatar"] as kotlin.String?,
      args["nickname"] as kotlin.String?,
      args["phone"] as kotlin.String?
  )
}

data class UpdateRegionInput(
    val name: kotlin.String? = null,
    val parentCode: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["name"] as kotlin.String?,
      args["parentCode"] as kotlin.String?
  )
}

data class UpdateTransactionInput(
    val adminNote: kotlin.String? = null,
    val freezeReason: kotlin.String? = null,
    val isFrozen: kotlin.Boolean? = null,
    val status: PaymentStatus? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["adminNote"] as kotlin.String?,
      args["freezeReason"] as kotlin.String?,
      args["isFrozen"] as kotlin.Boolean?,
      args["status"] as PaymentStatus?
  )
}

data class User(
    val avatarUrl: kotlin.String?,
    val createdAt: java.time.LocalDateTime,
    val id: kotlin.Long,
    val nickname: kotlin.String?,
    val phone: kotlin.String?,
    val updatedAt: java.time.LocalDateTime,
    val wechatOpenId: kotlin.String
)

data class UserInfo(
    val avatarUrl: kotlin.String?,
    val createdAt: java.time.LocalDateTime,
    val id: kotlin.Long,
    val nickname: kotlin.String?,
    val phone: kotlin.String?,
    val updatedAt: java.time.LocalDateTime,
    val wechatOpenId: kotlin.String
)

data class UserPaymentTransaction(
    val amount: java.math.BigDecimal,
    val completedAt: java.time.LocalDateTime?,
    val createdAt: java.time.LocalDateTime,
    val failureReason: kotlin.String?,
    val id: kotlin.String,
    val orderId: kotlin.Long,
    val orderNumber: kotlin.String,
    val paymentMethod: PaymentMethod,
    val refundAmount: java.math.BigDecimal?,
    val refundedAt: java.time.LocalDateTime?,
    val status: PaymentStatus,
    val transactionId: kotlin.String?
)

enum class UserRole(val label: String) {
      Admin("ADMIN"),
      None("NONE"),
      User("USER"),
      Worker("WORKER");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): UserRole? {
      return values().find { it.label == label }
    }
  }
}

enum class UserStatus(val label: String) {
      Active("ACTIVE"),
      Deleted("DELETED"),
      Inactive("INACTIVE"),
      Suspended("SUSPENDED");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): UserStatus? {
      return values().find { it.label == label }
    }
  }
}

data class ValidateAddressInput(
    val city: kotlin.String,
    val district: kotlin.String,
    val province: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["city"] as kotlin.String,
      args["district"] as kotlin.String,
      args["province"] as kotlin.String
  )
}

data class WeChatLoginResponse(
    val accessToken: kotlin.String,
    val expiresIn: kotlin.Int,
    val refreshToken: kotlin.String,
    val userInfo: UserInfo
)

data class WeChatTokenResponse(
    val accessToken: kotlin.String,
    val expiresIn: kotlin.Int,
    val refreshToken: kotlin.String
)

data class WechatCallbackInput(
    val appId: kotlin.String? = null,
    val mchId: kotlin.String? = null,
    val outTradeNo: kotlin.String? = null,
    val resource: kotlin.String,
    val resourceType: kotlin.String,
    val summary: kotlin.String,
    val transactionId: kotlin.String? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["appId"] as kotlin.String?,
      args["mchId"] as kotlin.String?,
      args["outTradeNo"] as kotlin.String?,
      args["resource"] as kotlin.String,
      args["resourceType"] as kotlin.String,
      args["summary"] as kotlin.String,
      args["transactionId"] as kotlin.String?
  )
}

data class WechatLoginInput(
    val code: kotlin.String
) {
  constructor(args: Map<String, Any>) : this(
      args["code"] as kotlin.String
  )
}

data class WeeklyStatistic(
    val endDate: kotlin.String,
    val orderCount: kotlin.Int,
    val revenue: java.math.BigDecimal,
    val startDate: kotlin.String,
    val weekNumber: kotlin.Int,
    val year: kotlin.Int
)

enum class WorkerStatus(val label: String) {
      Offline("OFFLINE"),
      Online("ONLINE");
        
  companion object {
    @JvmStatic
    fun valueOfLabel(label: String): WorkerStatus? {
      return values().find { it.label == label }
    }
  }
}