/*
 * This file was generated by Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

plugins {
    // Apply foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "AquaRush"
include(
    "modules:aqua-logging",
    "modules:aqua-common",
    "modules:aqua-api",
    "modules:aqua-user",
    "modules:aqua-product",
    "modules:aqua-order",
    "modules:aqua-delivery",
    "modules:aqua-payment",
    "modules:aqua-reconciliation",
    "modules:aqua-statistics",
    "modules:aqua-storage",
    "modules:aqua-notice",
    "modules:aqua-review",
    "modules:aqua-entry",
)