/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

kotlin {
    jvmToolchain(19)
}

dependencies {
    implementation(libs.kotlin.gradlePlugin)
    implementation(libs.spring.boot.gradlePlugin)
    implementation(libs.spring.dependency.management.gradlePlugin)

    // Add Kotlin plugins for precompiled script plugins
    implementation(libs.kotlin.allopen)
    implementation(libs.kotlin.noarg)

    // Add ktlint plugin
    implementation(libs.ktlint.gradlePlugin)
}
