// Generated by GraphQL Code Generator - DO NOT EDIT
export type Maybe<T> = T | null | undefined;
export type InputMaybe<T> = T | null | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  BigDecimal: { input: number; output: number; }
  JsonArray: { input: string[]; output: string[]; }
  JsonObject: { input: { [key: string]: any }; output: { [key: string]: any }; }
  LocalDateTime: { input: string; output: string; }
  Long: { input: number; output: number; }
  Map: { input: { [key: string]: any }; output: { [key: string]: any }; }
  Money: { input: string; output: string; }
  PrimaryId: { input: string; output: string; }
};

export type Address = {
  readonly city: Scalars['String']['output'];
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['PrimaryId']['output'];
  readonly isDefault: Scalars['Boolean']['output'];
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly phone: Scalars['String']['output'];
  readonly province: Scalars['String']['output'];
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
  readonly receiverName: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
};

export type AddressInput = {
  readonly city: Scalars['String']['input'];
  readonly cityCode: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly districtCode: Scalars['String']['input'];
  readonly isDefault?: Scalars['Boolean']['input'];
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly phone: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
  readonly provinceCode: Scalars['String']['input'];
  readonly receiverName: Scalars['String']['input'];
};

export type AddressValidationInput = {
  readonly city: Scalars['String']['input'];
  readonly cityCode?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly districtCode?: InputMaybe<Scalars['String']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province: Scalars['String']['input'];
  readonly provinceCode?: InputMaybe<Scalars['String']['input']>;
};

export type AddressValidationPayload = {
  readonly coordinatesValid: Scalars['Boolean']['output'];
  readonly errors: ReadonlyArray<Scalars['String']['output']>;
  readonly isDuplicate: Scalars['Boolean']['output'];
  readonly isValid: Scalars['Boolean']['output'];
  readonly message: Scalars['String']['output'];
  readonly normalizedAddress?: Maybe<NormalizedAddress>;
  readonly success: Scalars['Boolean']['output'];
};

export type Admin = {
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly lastLoginAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly realName?: Maybe<Scalars['String']['output']>;
  readonly role: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly username: Scalars['String']['output'];
};

export type AdminFavoriteListInput = {
  readonly dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly page?: InputMaybe<Scalars['Int']['input']>;
  readonly productId?: InputMaybe<Scalars['PrimaryId']['input']>;
  readonly productStatus?: InputMaybe<ProductStatus>;
  readonly search?: InputMaybe<Scalars['String']['input']>;
  readonly size?: InputMaybe<Scalars['Int']['input']>;
  readonly sortBy?: FavoriteSortBy;
  readonly userId?: InputMaybe<Scalars['PrimaryId']['input']>;
};

export enum AdminRole {
  ADMIN = 'ADMIN',
  DELIVERY_WORKER = 'DELIVERY_WORKER',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export type AllProductsFavoriteStats = {
  readonly averageFavoritesPerProduct: Scalars['Float']['output'];
  readonly totalFavorites: Scalars['Long']['output'];
  readonly totalProducts: Scalars['Long']['output'];
};

export type AuthPayload = {
  readonly accessToken: Scalars['String']['output'];
  readonly refreshToken: Scalars['String']['output'];
  readonly user: User;
};

export enum BatchFavoriteOperation {
  ANALYZE_FAVORITES = 'ANALYZE_FAVORITES',
  CLEAR_ALL_FAVORITES = 'CLEAR_ALL_FAVORITES',
  CLEAR_SPECIFIC_PRODUCTS = 'CLEAR_SPECIFIC_PRODUCTS',
  EXPORT_FAVORITES = 'EXPORT_FAVORITES'
}

export type BatchFavoriteOperationInput = {
  readonly operation: BatchFavoriteOperation;
  readonly productIds: ReadonlyArray<Scalars['PrimaryId']['input']>;
  readonly reason?: InputMaybe<Scalars['String']['input']>;
  readonly userIds: ReadonlyArray<Scalars['PrimaryId']['input']>;
};

export type BatchOperationResult = {
  readonly details: Scalars['Map']['output'];
  readonly errors: ReadonlyArray<Scalars['String']['output']>;
  readonly failureCount: Scalars['Int']['output'];
  readonly message: Scalars['String']['output'];
  readonly processedCount: Scalars['Int']['output'];
  readonly success: Scalars['Boolean']['output'];
  readonly successCount: Scalars['Int']['output'];
};

export type BatchStockAdjustmentInput = {
  readonly adjustments: ReadonlyArray<StockAdjustmentInput>;
};

export type BatchStockAdjustmentResult = {
  readonly failureCount: Scalars['Int']['output'];
  readonly results: ReadonlyArray<StockAdjustmentResult>;
  readonly success: Scalars['Boolean']['output'];
  readonly successCount: Scalars['Int']['output'];
};

export type BindDeliveryPhoneInput = {
  readonly openId: Scalars['String']['input'];
  readonly phoneNumber: Scalars['String']['input'];
};

export type BooleanPayload = {
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type BucketDeposit = {
  readonly amountCents: Scalars['Long']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly paymentTime?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly paymentTransactionId?: Maybe<Scalars['String']['output']>;
  readonly quantity: Scalars['Int']['output'];
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly refundedBy?: Maybe<Scalars['PrimaryId']['output']>;
  readonly remark?: Maybe<Scalars['String']['output']>;
  readonly status: BucketDepositStatus;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
};

export type BucketDepositPage = {
  readonly list: ReadonlyArray<BucketDeposit>;
  readonly pageInfo: PageInfo;
};

export enum BucketDepositStatus {
  DEPOSITED = 'DEPOSITED',
  REFUNDED = 'REFUNDED'
}

export type ClientMessage = {
  readonly content: Scalars['String']['output'];
  readonly data?: Maybe<Scalars['Map']['output']>;
  readonly id: Scalars['PrimaryId']['output'];
  readonly isRead: Scalars['Boolean']['output'];
  readonly messageType: Scalars['String']['output'];
  readonly readAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly sentAt: Scalars['LocalDateTime']['output'];
  readonly title?: Maybe<Scalars['String']['output']>;
};

export type CreateAdminInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly password?: InputMaybe<Scalars['String']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly realName?: InputMaybe<Scalars['String']['input']>;
  readonly role: AdminRole;
  readonly status?: InputMaybe<DeliveryWorkerStatus>;
  readonly username: Scalars['String']['input'];
};

export type CreateBucketDepositInput = {
  readonly quantity: Scalars['Int']['input'];
};

export type CreateDeliveryAddressInput = {
  readonly city: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province: Scalars['String']['input'];
  readonly receiverName: Scalars['String']['input'];
  readonly receiverPhone: Scalars['String']['input'];
};

export type CreateDeliveryAreaInput = {
  readonly city: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly enabled?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type CreateDeliveryWorkerInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly coordinates?: InputMaybe<Scalars['String']['input']>;
  readonly currentLocation?: InputMaybe<Scalars['String']['input']>;
  readonly earning?: InputMaybe<Scalars['Money']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name: Scalars['String']['input'];
  readonly phone: Scalars['String']['input'];
  readonly rating?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly wechatOpenId: Scalars['String']['input'];
};

export type CreateManualRefundInput = {
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly amount: Scalars['Money']['input'];
  readonly orderId: Scalars['PrimaryId']['input'];
  readonly originalTransactionId: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
  readonly userId: Scalars['PrimaryId']['input'];
};

export type CreateOrderInput = {
  readonly addressId: Scalars['PrimaryId']['input'];
  readonly productId: Scalars['PrimaryId']['input'];
  readonly quantity: Scalars['Int']['input'];
};

export type CreateProductInput = {
  readonly certificateImages?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly coverImageUrl: Scalars['String']['input'];
  readonly deliverySettings?: InputMaybe<Scalars['JsonObject']['input']>;
  readonly depositPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly detailContent?: InputMaybe<Scalars['String']['input']>;
  readonly imageGallery?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly mineralContent?: InputMaybe<Scalars['String']['input']>;
  readonly name: Scalars['String']['input'];
  readonly originalPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly price: Scalars['Money']['input'];
  readonly salesVolume: Scalars['Int']['input'];
  readonly sortOrder: Scalars['Int']['input'];
  readonly specification: Scalars['String']['input'];
  readonly status: ProductStatus;
  readonly stock: Scalars['Int']['input'];
  readonly subtitle?: InputMaybe<Scalars['String']['input']>;
  readonly tags?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly waterSource?: InputMaybe<Scalars['String']['input']>;
};

export type CreateRegionInput = {
  readonly code: Scalars['String']['input'];
  readonly level: Scalars['Int']['input'];
  readonly name: Scalars['String']['input'];
  readonly parentCode?: InputMaybe<Scalars['String']['input']>;
};

export type CreateReviewRequest = {
  readonly comment?: InputMaybe<Scalars['String']['input']>;
  readonly deliveryWorkerId: Scalars['PrimaryId']['input'];
  readonly isAnonymous?: InputMaybe<Scalars['Boolean']['input']>;
  readonly orderId: Scalars['PrimaryId']['input'];
  readonly rating: Scalars['Int']['input'];
};

export type CreateWechatPaymentInput = {
  readonly amount: Scalars['Money']['input'];
  readonly description: Scalars['String']['input'];
  readonly orderId: Scalars['PrimaryId']['input'];
};

export type CustomPageRequest = {
  readonly page?: InputMaybe<Scalars['Int']['input']>;
  readonly size?: InputMaybe<Scalars['Int']['input']>;
};

export type DailyPaymentStats = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly date: Scalars['String']['output'];
  readonly failedTransactions: Scalars['Long']['output'];
  readonly paymentMethodBreakdown: ReadonlyArray<PaymentMethodStats>;
  readonly peakHour: Scalars['Int']['output'];
  readonly refundCount: Scalars['Long']['output'];
  readonly refundedAmount: Scalars['Money']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export type DailyStatistic = {
  readonly date: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
};

export type DateRange = {
  readonly endDate: Scalars['LocalDateTime']['output'];
  readonly startDate: Scalars['LocalDateTime']['output'];
};

export type DateRangeInput = {
  readonly endDate: Scalars['LocalDateTime']['input'];
  readonly startDate: Scalars['LocalDateTime']['input'];
};

export type DeliveryAddress = {
  readonly city: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly province: Scalars['String']['output'];
  readonly receiverName: Scalars['String']['output'];
  readonly receiverPhone: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
};

export type DeliveryArea = {
  readonly city: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly enabled: Scalars['Boolean']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly name: Scalars['String']['output'];
  readonly province: Scalars['String']['output'];
};

export type DeliveryLoginInput = {
  readonly code: Scalars['String']['input'];
};

export type DeliveryLoginResponse = {
  readonly message?: Maybe<Scalars['String']['output']>;
  readonly needBindPhone: Scalars['Boolean']['output'];
  readonly openId?: Maybe<Scalars['String']['output']>;
  readonly refreshToken?: Maybe<Scalars['String']['output']>;
  readonly token?: Maybe<Scalars['String']['output']>;
  readonly workerInfo?: Maybe<DeliveryWorkerInfo>;
};

export type DeliveryWorker = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly averageRating?: Maybe<Scalars['BigDecimal']['output']>;
  readonly completedOrders: Scalars['Int']['output'];
  readonly coordinates?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly currentLocation?: Maybe<Scalars['String']['output']>;
  readonly earning?: Maybe<Scalars['Money']['output']>;
  readonly id: Scalars['PrimaryId']['output'];
  readonly isAvailable: Scalars['Boolean']['output'];
  readonly name: Scalars['String']['output'];
  readonly onlineStatus: DeliveryWorkerStatus;
  readonly phone: Scalars['String']['output'];
  readonly rating?: Maybe<Scalars['BigDecimal']['output']>;
  readonly totalOrders: Scalars['Int']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type DeliveryWorkerInfo = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['ID']['output'];
  readonly name: Scalars['String']['output'];
  readonly phone: Scalars['String']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type DeliveryWorkerRankingResponse = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly positiveRatingPercentage: Scalars['Float']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly workerId: Scalars['PrimaryId']['output'];
  readonly workerName?: Maybe<Scalars['String']['output']>;
};

export type DeliveryWorkerStatistics = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly deliveryWorkerId: Scalars['PrimaryId']['output'];
  readonly fiveStarReviews: Scalars['Long']['output'];
  readonly fourStarReviews: Scalars['Long']['output'];
  readonly oneStarReviews: Scalars['Long']['output'];
  readonly threeStarReviews: Scalars['Long']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly twoStarReviews: Scalars['Long']['output'];
};

export type DeliveryWorkerStatisticsResponse = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly deliveryWorkerId: Scalars['PrimaryId']['output'];
  readonly fiveStarReviews: Scalars['Long']['output'];
  readonly fourStarReviews: Scalars['Long']['output'];
  readonly lastUpdated: Scalars['LocalDateTime']['output'];
  readonly oneStarReviews: Scalars['Long']['output'];
  readonly ratingDistribution: Scalars['Map']['output'];
  readonly threeStarReviews: Scalars['Long']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly twoStarReviews: Scalars['Long']['output'];
  readonly workerName?: Maybe<Scalars['String']['output']>;
};

export enum DeliveryWorkerStatus {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE'
}

export type DistancePayload = {
  readonly distanceKm?: Maybe<Scalars['Float']['output']>;
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type DoNotDisturbSettings = {
  readonly enabled: Scalars['Boolean']['output'];
  readonly endTime?: Maybe<Scalars['String']['output']>;
  readonly startTime?: Maybe<Scalars['String']['output']>;
};

export type ExportFavoritesInput = {
  readonly dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly format?: ExportFormat;
  readonly includeProductInfo?: Scalars['Boolean']['input'];
  readonly includeUserInfo?: Scalars['Boolean']['input'];
  readonly productIds?: InputMaybe<ReadonlyArray<Scalars['PrimaryId']['input']>>;
  readonly userId?: InputMaybe<Scalars['PrimaryId']['input']>;
};

export type ExportFavoritesResult = {
  readonly downloadUrl?: Maybe<Scalars['String']['output']>;
  readonly expiresAt: Scalars['LocalDateTime']['output'];
  readonly fileName: Scalars['String']['output'];
  readonly fileSize: Scalars['Long']['output'];
  readonly message: Scalars['String']['output'];
  readonly recordCount: Scalars['Int']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export enum ExportFormat {
  CSV = 'CSV',
  EXCEL = 'EXCEL',
  JSON = 'JSON'
}

export type ExportTransactionsInput = {
  readonly dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly format?: Scalars['String']['input'];
  readonly includeMetadata?: Scalars['Boolean']['input'];
  readonly maxAmount?: InputMaybe<Scalars['Money']['input']>;
  readonly minAmount?: InputMaybe<Scalars['Money']['input']>;
  readonly paymentMethod?: InputMaybe<PaymentMethod>;
  readonly status?: InputMaybe<PaymentStatus>;
  readonly userId?: InputMaybe<Scalars['PrimaryId']['input']>;
};

export type FavoriteProduct = {
  readonly addedAt: Scalars['LocalDateTime']['output'];
  readonly coverImageUrl: Scalars['String']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly name: Scalars['String']['output'];
  readonly originalPrice?: Maybe<Scalars['Money']['output']>;
  readonly price: Scalars['Money']['output'];
  readonly salesVolume: Scalars['Int']['output'];
  readonly status: ProductStatus;
  readonly stock: Scalars['Int']['output'];
  readonly subtitle?: Maybe<Scalars['String']['output']>;
};

export type FavoriteProductPage = {
  readonly list: ReadonlyArray<FavoriteProduct>;
  readonly pageInfo: PageInfo;
};

export type FavoriteProductStats = {
  readonly addToOrderRate: Scalars['Float']['output'];
  readonly averageTimeToOrder: Scalars['Float']['output'];
  readonly favoriteCount: Scalars['Long']['output'];
  readonly productId: Scalars['PrimaryId']['output'];
  readonly productName: Scalars['String']['output'];
  readonly revenueFromFavorites: Scalars['Money']['output'];
};

export enum FavoriteSortBy {
  CREATED_AT_ASC = 'CREATED_AT_ASC',
  CREATED_AT_DESC = 'CREATED_AT_DESC',
  PRODUCT_ID_ASC = 'PRODUCT_ID_ASC',
  PRODUCT_ID_DESC = 'PRODUCT_ID_DESC',
  PRODUCT_NAME_ASC = 'PRODUCT_NAME_ASC',
  PRODUCT_NAME_DESC = 'PRODUCT_NAME_DESC',
  PRODUCT_PRICE_ASC = 'PRODUCT_PRICE_ASC',
  PRODUCT_PRICE_DESC = 'PRODUCT_PRICE_DESC',
  USER_ID_ASC = 'USER_ID_ASC',
  USER_ID_DESC = 'USER_ID_DESC'
}

export type FavoriteTrendData = {
  readonly activeUsers: Scalars['Long']['output'];
  readonly date: Scalars['String']['output'];
  readonly newFavorites: Scalars['Long']['output'];
  readonly totalFavorites: Scalars['Long']['output'];
};

export type GeocodeInput = {
  readonly city: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type GeocodePayload = {
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type LowStockAlert = {
  readonly currentStock: Scalars['Int']['output'];
  readonly productId: Scalars['PrimaryId']['output'];
  readonly productName: Scalars['String']['output'];
  readonly status: ProductStatus;
  readonly threshold: Scalars['Int']['output'];
};

export type MessageHistoryPage = {
  readonly list: ReadonlyArray<ClientMessage>;
  readonly pageInfo: PageInfo;
};

export type MessageStatistics = {
  readonly messageTypes: Scalars['Map']['output'];
  readonly readMessages: Scalars['Long']['output'];
  readonly totalMessages: Scalars['Long']['output'];
  readonly unreadMessages: Scalars['Long']['output'];
};

export type MessageTypeInfo = {
  readonly description: Scalars['String']['output'];
  readonly name: Scalars['String']['output'];
  readonly type: Scalars['String']['output'];
};

export type MonthlyStatistic = {
  readonly month: Scalars['Int']['output'];
  readonly monthName: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
  readonly year: Scalars['Int']['output'];
};

export type Mutation = {
  readonly acceptDelivery: Order;
  readonly analyzeUserFavorites: Scalars['Map']['output'];
  readonly assignDeliveryWorker: Order;
  readonly batchAdjustStock: BatchStockAdjustmentResult;
  readonly batchAssignOrders: ReadonlyArray<Order>;
  readonly batchFavoriteOperation: BatchOperationResult;
  readonly batchUpdateProducts: ReadonlyArray<Product>;
  readonly bindDeliveryPhone: DeliveryLoginResponse;
  readonly cancelOrder: Order;
  readonly completeDelivery: Order;
  readonly createAddress: Address;
  readonly createAdmin: Admin;
  readonly createDeliveryAddress: DeliveryAddress;
  readonly createDeliveryArea: DeliveryArea;
  readonly createDeliveryWorker: DeliveryWorker;
  readonly createManualRefund: RefundRequest;
  readonly createOrder: Order;
  readonly createProduct: Product;
  readonly createRegion: Region;
  readonly createReview: Review;
  readonly createWechatPayment: PaymentData;
  readonly decreaseStock: Scalars['Boolean']['output'];
  readonly deleteAddress: Scalars['Boolean']['output'];
  readonly deleteAdmin: Scalars['Boolean']['output'];
  readonly deleteDeliveryAddress: Scalars['Boolean']['output'];
  readonly deleteDeliveryArea: Scalars['Boolean']['output'];
  readonly deleteDeliveryWorker: Scalars['Boolean']['output'];
  readonly deleteMessage: Scalars['Boolean']['output'];
  readonly deleteMessages: Scalars['Boolean']['output'];
  readonly deleteProduct: Scalars['Boolean']['output'];
  readonly deleteRegion: Scalars['Boolean']['output'];
  readonly deliveryLogin: DeliveryLoginResponse;
  readonly disableAllNotifications: UserNotificationSettings;
  readonly enableAllNotifications: UserNotificationSettings;
  readonly exportFavorites: ExportFavoritesResult;
  readonly exportTransactions: Scalars['String']['output'];
  readonly forceCompletePayment: Scalars['Boolean']['output'];
  readonly forceRefund: Scalars['Boolean']['output'];
  readonly freezeSuspiciousTransaction: Scalars['Boolean']['output'];
  readonly geocodeAddress: GeocodePayload;
  readonly handleWechatCallback: Scalars['String']['output'];
  readonly increaseStock: Scalars['String']['output'];
  readonly logout: Scalars['Boolean']['output'];
  readonly markMessageAsRead: Scalars['Boolean']['output'];
  readonly markMessagesAsRead: Scalars['Boolean']['output'];
  readonly offlineProduct: Product;
  readonly onlineProduct: Product;
  readonly processRefund: RefundRequest;
  readonly processSuspiciousTransaction: SuspiciousTransaction;
  readonly refreshFavoriteAnalyticsCache: BooleanPayload;
  readonly refreshToken: WeChatTokenResponse;
  readonly refund: Scalars['Boolean']['output'];
  readonly requestPushPermission: Scalars['String']['output'];
  readonly requestRefund: RefundRequest;
  readonly reverseGeocode: ReverseGeocodePayload;
  readonly setDefaultAddress: Scalars['Boolean']['output'];
  readonly setDefaultDeliveryAddress: Scalars['Boolean']['output'];
  readonly setDoNotDisturb: Scalars['Boolean']['output'];
  readonly startDelivery: Order;
  readonly subscribeToTopic: Scalars['Boolean']['output'];
  readonly testNotification: Scalars['String']['output'];
  readonly toggleProductFavorites: Scalars['Boolean']['output'];
  readonly unsubscribeFromTopic: Scalars['Boolean']['output'];
  readonly updateAddress: Address;
  readonly updateAdmin: Admin;
  readonly updateDeliveryAddress: DeliveryAddress;
  readonly updateDeliveryArea: DeliveryArea;
  readonly updateDeliveryWorker: DeliveryWorker;
  readonly updateNotificationSettings: UserNotificationSettings;
  readonly updateOrderStatus: Order;
  readonly updateProduct: Product;
  readonly updateProductStatus: Product;
  readonly updateProfile: UserInfo;
  readonly updateRegion: Region;
  readonly updateTransaction: PaymentTransaction;
  readonly updateTransactionNote: Scalars['Boolean']['output'];
  readonly updateWorkerStatus: DeliveryWorker;
  readonly validateAddress: AddressValidationPayload;
  readonly wechatLogin: WeChatLoginResponse;
};


export type MutationAcceptDeliveryArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type MutationAnalyzeUserFavoritesArgs = {
  userId: Scalars['PrimaryId']['input'];
};


export type MutationAssignDeliveryWorkerArgs = {
  isSelfCollect: Scalars['Boolean']['input'];
  orderId: Scalars['PrimaryId']['input'];
  workerId: Scalars['PrimaryId']['input'];
};


export type MutationBatchAdjustStockArgs = {
  input: BatchStockAdjustmentInput;
};


export type MutationBatchAssignOrdersArgs = {
  orderIds: ReadonlyArray<Scalars['PrimaryId']['input']>;
  workerId: Scalars['PrimaryId']['input'];
};


export type MutationBatchFavoriteOperationArgs = {
  input: BatchFavoriteOperationInput;
};


export type MutationBatchUpdateProductsArgs = {
  input: ReadonlyArray<ProductUpdateRequest>;
};


export type MutationBindDeliveryPhoneArgs = {
  input: BindDeliveryPhoneInput;
};


export type MutationCancelOrderArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type MutationCompleteDeliveryArgs = {
  orderId: Scalars['PrimaryId']['input'];
  paymentType?: InputMaybe<PaymentType>;
  photos: ReadonlyArray<Scalars['String']['input']>;
};


export type MutationCreateAddressArgs = {
  input: AddressInput;
};


export type MutationCreateAdminArgs = {
  input: CreateAdminInput;
};


export type MutationCreateDeliveryAddressArgs = {
  input: CreateDeliveryAddressInput;
};


export type MutationCreateDeliveryAreaArgs = {
  input: CreateDeliveryAreaInput;
};


export type MutationCreateDeliveryWorkerArgs = {
  input: CreateDeliveryWorkerInput;
};


export type MutationCreateManualRefundArgs = {
  input: CreateManualRefundInput;
};


export type MutationCreateOrderArgs = {
  input: CreateOrderInput;
};


export type MutationCreateProductArgs = {
  input: CreateProductInput;
};


export type MutationCreateRegionArgs = {
  input: CreateRegionInput;
};


export type MutationCreateReviewArgs = {
  input: CreateReviewRequest;
};


export type MutationCreateWechatPaymentArgs = {
  input: CreateWechatPaymentInput;
};


export type MutationDecreaseStockArgs = {
  productId: Scalars['PrimaryId']['input'];
  quantity: Scalars['Int']['input'];
};


export type MutationDeleteAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationDeleteAdminArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationDeleteDeliveryAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationDeleteDeliveryAreaArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationDeleteDeliveryWorkerArgs = {
  workerId: Scalars['PrimaryId']['input'];
};


export type MutationDeleteMessageArgs = {
  messageId: Scalars['PrimaryId']['input'];
};


export type MutationDeleteMessagesArgs = {
  messageIds: ReadonlyArray<Scalars['PrimaryId']['input']>;
};


export type MutationDeleteProductArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationDeleteRegionArgs = {
  code: Scalars['String']['input'];
};


export type MutationDeliveryLoginArgs = {
  input: DeliveryLoginInput;
};


export type MutationExportFavoritesArgs = {
  input: ExportFavoritesInput;
};


export type MutationExportTransactionsArgs = {
  input: ExportTransactionsInput;
};


export type MutationForceCompletePaymentArgs = {
  adminNote: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationForceRefundArgs = {
  adminNote: Scalars['String']['input'];
  amount: Scalars['BigDecimal']['input'];
  reason: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationFreezeSuspiciousTransactionArgs = {
  reason: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationGeocodeAddressArgs = {
  address: GeocodeInput;
};


export type MutationHandleWechatCallbackArgs = {
  input: WechatCallbackInput;
};


export type MutationIncreaseStockArgs = {
  productId: Scalars['PrimaryId']['input'];
  quantity: Scalars['Int']['input'];
};


export type MutationMarkMessageAsReadArgs = {
  messageId: Scalars['PrimaryId']['input'];
};


export type MutationMarkMessagesAsReadArgs = {
  messageIds: ReadonlyArray<Scalars['PrimaryId']['input']>;
};


export type MutationOfflineProductArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationOnlineProductArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationProcessRefundArgs = {
  input: ProcessRefundInput;
};


export type MutationProcessSuspiciousTransactionArgs = {
  input: ProcessSuspiciousTransactionInput;
};


export type MutationRefreshFavoriteAnalyticsCacheArgs = {
  force?: InputMaybe<Scalars['Boolean']['input']>;
};


export type MutationRefreshTokenArgs = {
  input: RefreshTokenInput;
};


export type MutationRefundArgs = {
  input: RefundInput;
};


export type MutationRequestRefundArgs = {
  input: RequestRefundInput;
};


export type MutationReverseGeocodeArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type MutationSetDefaultAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationSetDefaultDeliveryAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type MutationSetDoNotDisturbArgs = {
  enabled: Scalars['Boolean']['input'];
  endTime?: InputMaybe<Scalars['String']['input']>;
  startTime?: InputMaybe<Scalars['String']['input']>;
};


export type MutationStartDeliveryArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type MutationSubscribeToTopicArgs = {
  topic: Scalars['String']['input'];
};


export type MutationToggleProductFavoritesArgs = {
  productId: Scalars['PrimaryId']['input'];
};


export type MutationUnsubscribeFromTopicArgs = {
  topic: Scalars['String']['input'];
};


export type MutationUpdateAddressArgs = {
  id: Scalars['PrimaryId']['input'];
  input: UpdateAddressInput;
};


export type MutationUpdateAdminArgs = {
  id: Scalars['PrimaryId']['input'];
  input: UpdateAdminInput;
};


export type MutationUpdateDeliveryAddressArgs = {
  id: Scalars['PrimaryId']['input'];
  input: UpdateDeliveryAddressInput;
};


export type MutationUpdateDeliveryAreaArgs = {
  id: Scalars['PrimaryId']['input'];
  input: CreateDeliveryAreaInput;
};


export type MutationUpdateDeliveryWorkerArgs = {
  input: UpdateDeliveryWorkerInput;
  workerId: Scalars['PrimaryId']['input'];
};


export type MutationUpdateNotificationSettingsArgs = {
  input: UpdateNotificationSettingsInput;
};


export type MutationUpdateOrderStatusArgs = {
  orderId: Scalars['PrimaryId']['input'];
  status: OrderStatus;
};


export type MutationUpdateProductArgs = {
  id: Scalars['PrimaryId']['input'];
  input: UpdateProductInput;
};


export type MutationUpdateProductStatusArgs = {
  productId: Scalars['PrimaryId']['input'];
  status: ProductStatus;
};


export type MutationUpdateProfileArgs = {
  input: UpdateProfileInput;
};


export type MutationUpdateRegionArgs = {
  code: Scalars['String']['input'];
  input: UpdateRegionInput;
};


export type MutationUpdateTransactionArgs = {
  input: UpdateTransactionInput;
  transactionId: Scalars['String']['input'];
};


export type MutationUpdateTransactionNoteArgs = {
  note: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationUpdateWorkerStatusArgs = {
  status: DeliveryWorkerStatus;
  workerId: Scalars['PrimaryId']['input'];
};


export type MutationValidateAddressArgs = {
  input: AddressValidationInput;
};


export type MutationWechatLoginArgs = {
  input: WechatLoginInput;
};

export type NearbyAddressesPayload = {
  readonly addresses: ReadonlyArray<Address>;
  readonly distanceMap: Scalars['Map']['output'];
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type NormalizedAddress = {
  readonly city: Scalars['String']['output'];
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly province: Scalars['String']['output'];
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
};

export type Order = {
  readonly address: Address;
  readonly amount: Scalars['Money']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliveryConfirmedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly deliveryPhotos?: Maybe<ReadonlyArray<Scalars['String']['output']>>;
  readonly deliveryStartedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly deliveryWorker?: Maybe<DeliveryWorker>;
  readonly id: Scalars['PrimaryId']['output'];
  readonly isSelfCollect: Scalars['Boolean']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paymentMethod?: Maybe<Scalars['String']['output']>;
  readonly paymentTime?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly paymentTransactionId?: Maybe<Scalars['String']['output']>;
  readonly paymentType?: Maybe<PaymentType>;
  readonly product: Product;
  readonly quantity: Scalars['Int']['output'];
  readonly status: OrderStatus;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly user: User;
};

export type OrderPaymentInfo = {
  readonly amount: Scalars['Money']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paidAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly paymentMethod: PaymentMethod;
  readonly refundAmount?: Maybe<Scalars['Money']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
};

export type OrderReviewCheckResponse = {
  readonly canReview: Scalars['Boolean']['output'];
  readonly hasReviewed: Scalars['Boolean']['output'];
  readonly review?: Maybe<Review>;
};

export type OrderStatistics = {
  readonly averageOrderValue: Scalars['Money']['output'];
  readonly dateRange: DateRange;
  readonly totalOrders: Scalars['Int']['output'];
  readonly totalRevenue: Scalars['Money']['output'];
};

export enum OrderStatus {
  CANCELLED = 'CANCELLED',
  CONFIRMED = 'CONFIRMED',
  DELIVERED = 'DELIVERED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  REFUNDED = 'REFUNDED'
}

export type PageInfo = {
  readonly hasNext: Scalars['Boolean']['output'];
  readonly hasPrevious: Scalars['Boolean']['output'];
  readonly pageNum: Scalars['Int']['output'];
  readonly pageSize: Scalars['Int']['output'];
  readonly total: Scalars['Int']['output'];
  readonly totalPages: Scalars['Int']['output'];
};

export type PaymentData = {
  readonly appId: Scalars['String']['output'];
  readonly codeUrl: Scalars['String']['output'];
  readonly nonceStr: Scalars['String']['output'];
  readonly outTradeNo: Scalars['String']['output'];
  readonly packageValue: Scalars['String']['output'];
  readonly paySign: Scalars['String']['output'];
  readonly signType: Scalars['String']['output'];
  readonly timeStamp: Scalars['String']['output'];
};

export enum PaymentMethod {
  ALIPAY = 'ALIPAY',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  WECHAT_PAY = 'WECHAT_PAY'
}

export type PaymentMethodStats = {
  readonly averageAmount: Scalars['Money']['output'];
  readonly failureCount: Scalars['Long']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly refundCount: Scalars['Long']['output'];
  readonly successCount: Scalars['Long']['output'];
  readonly successRate: Scalars['Float']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly transactionCount: Scalars['Long']['output'];
};

export type PaymentPeriodStats = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly failedTransactions: Scalars['Long']['output'];
  readonly paymentMethodBreakdown: ReadonlyArray<PaymentMethodStats>;
  readonly period: Scalars['String']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export type PaymentStatistics = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly dailyStats: ReadonlyArray<DailyPaymentStats>;
  readonly failedTransactions: Scalars['Long']['output'];
  readonly refundCount: Scalars['Long']['output'];
  readonly refundedAmount: Scalars['Money']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export enum PaymentStatus {
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  REFUNDED = 'REFUNDED',
  SUCCESS = 'SUCCESS'
}

export type PaymentStatusInfo = {
  readonly amount: Scalars['BigDecimal']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly orderNumber: Scalars['String']['output'];
  readonly paidAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly refundAmount?: Maybe<Scalars['BigDecimal']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
};

export type PaymentTransaction = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly externalTransactionId?: Maybe<Scalars['String']['output']>;
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly gateway: Scalars['String']['output'];
  readonly id: Scalars['String']['output'];
  readonly metadata?: Maybe<Scalars['Map']['output']>;
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
};

export enum PaymentType {
  CASH = 'CASH',
  QR_CODE = 'QR_CODE',
  WATER_TICKET = 'WATER_TICKET'
}

export type ProcessRefundInput = {
  readonly action: RefundAction;
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly amount: Scalars['Money']['input'];
  readonly orderId: Scalars['PrimaryId']['input'];
  readonly originalTransactionId: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
  readonly refundRequestId: Scalars['String']['input'];
  readonly userId: Scalars['PrimaryId']['input'];
};

export type ProcessSuspiciousTransactionInput = {
  readonly action: Scalars['String']['input'];
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly transactionId: Scalars['String']['input'];
};

export type Product = {
  readonly certificateImages?: Maybe<Scalars['JsonArray']['output']>;
  readonly coverImageUrl: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliverySettings?: Maybe<Scalars['JsonObject']['output']>;
  readonly depositPrice?: Maybe<Scalars['Money']['output']>;
  readonly detailContent?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['PrimaryId']['output'];
  readonly imageGallery?: Maybe<Scalars['JsonArray']['output']>;
  readonly mineralContent?: Maybe<Scalars['String']['output']>;
  readonly name: Scalars['String']['output'];
  readonly originalPrice?: Maybe<Scalars['Money']['output']>;
  readonly price: Scalars['Money']['output'];
  readonly salesVolume: Scalars['Int']['output'];
  readonly sortOrder: Scalars['Int']['output'];
  readonly specification: Scalars['String']['output'];
  readonly status: ProductStatus;
  readonly stock: Scalars['Int']['output'];
  readonly subtitle?: Maybe<Scalars['String']['output']>;
  readonly tags?: Maybe<Scalars['JsonArray']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly waterSource?: Maybe<Scalars['String']['output']>;
};

export type ProductFavoriteCount = {
  readonly addedThisMonth: Scalars['Long']['output'];
  readonly addedThisWeek: Scalars['Long']['output'];
  readonly addedToday: Scalars['Long']['output'];
  readonly favoriteCount: Scalars['Long']['output'];
  readonly product: Product;
};

export type ProductFavoriteItem = {
  readonly favoriteCount: Scalars['Long']['output'];
  readonly lastFavoritedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly product: Product;
};

export type ProductFavoritePage = {
  readonly list: ReadonlyArray<ProductFavoriteItem>;
  readonly pageInfo: PageInfo;
};

export type ProductListInput = {
  readonly maxPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly maxStock?: InputMaybe<Scalars['Int']['input']>;
  readonly minPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly minStock?: InputMaybe<Scalars['Int']['input']>;
  readonly page?: InputMaybe<Scalars['Int']['input']>;
  readonly search?: InputMaybe<Scalars['String']['input']>;
  readonly size?: InputMaybe<Scalars['Int']['input']>;
  readonly sort?: InputMaybe<Scalars['String']['input']>;
  readonly status?: InputMaybe<ProductStatus>;
};

export type ProductPage = {
  readonly list: ReadonlyArray<Product>;
  readonly pageInfo: PageInfo;
};

export type ProductSalesInfo = {
  readonly product: Product;
  readonly revenue: Scalars['Money']['output'];
  readonly salesPercentage: Scalars['Float']['output'];
  readonly salesVolume: Scalars['Int']['output'];
};

export type ProductSearchInput = {
  readonly hasDepositPrice?: InputMaybe<Scalars['Boolean']['input']>;
  readonly hasOriginalPrice?: InputMaybe<Scalars['Boolean']['input']>;
  readonly keyword?: InputMaybe<Scalars['String']['input']>;
  readonly maxPh?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly maxSalesVolume?: InputMaybe<Scalars['Int']['input']>;
  readonly minPh?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly minSalesVolume?: InputMaybe<Scalars['Int']['input']>;
  readonly sortBy?: ProductSortBy;
  readonly tags?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  readonly waterSource?: InputMaybe<Scalars['String']['input']>;
};

export enum ProductSortBy {
  CREATED_AT_ASC = 'CREATED_AT_ASC',
  CREATED_AT_DESC = 'CREATED_AT_DESC',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  PRICE_ASC = 'PRICE_ASC',
  PRICE_DESC = 'PRICE_DESC',
  SALES_VOLUME_ASC = 'SALES_VOLUME_ASC',
  SALES_VOLUME_DESC = 'SALES_VOLUME_DESC',
  SORT_ORDER_ASC = 'SORT_ORDER_ASC',
  SORT_ORDER_DESC = 'SORT_ORDER_DESC'
}

export type ProductStatistics = {
  readonly averagePrice: Scalars['Money']['output'];
  readonly lowStockProducts: Scalars['Int']['output'];
  readonly offlineProducts: Scalars['Int']['output'];
  readonly onlineProducts: Scalars['Int']['output'];
  readonly totalProducts: Scalars['Int']['output'];
  readonly totalValue: Scalars['Money']['output'];
};

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  OUT_OF_STOCK = 'OUT_OF_STOCK'
}

export type ProductUpdateRequest = {
  readonly certificateImages?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly coverImageUrl?: InputMaybe<Scalars['String']['input']>;
  readonly deliverySettings?: InputMaybe<Scalars['JsonObject']['input']>;
  readonly depositPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly detailContent?: InputMaybe<Scalars['String']['input']>;
  readonly id: Scalars['PrimaryId']['input'];
  readonly imageGallery?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly mineralContent?: InputMaybe<Scalars['String']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly originalPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly price?: InputMaybe<Scalars['Money']['input']>;
  readonly salesVolume?: InputMaybe<Scalars['Int']['input']>;
  readonly sortOrder?: InputMaybe<Scalars['Int']['input']>;
  readonly specification?: InputMaybe<Scalars['String']['input']>;
  readonly status?: InputMaybe<ProductStatus>;
  readonly stock?: InputMaybe<Scalars['Int']['input']>;
  readonly subtitle?: InputMaybe<Scalars['String']['input']>;
  readonly tags?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly waterSource?: InputMaybe<Scalars['String']['input']>;
};

export type Query = {
  readonly activeProducts: ProductPage;
  readonly activeProductsByStatus: ReadonlyArray<Product>;
  readonly address?: Maybe<Address>;
  readonly addresses: ReadonlyArray<Address>;
  readonly admin?: Maybe<Admin>;
  readonly admins: ReadonlyArray<Admin>;
  readonly allActiveProducts: ReadonlyArray<Product>;
  readonly allProducts: ReadonlyArray<Product>;
  readonly allProductsFavoriteStats: AllProductsFavoriteStats;
  readonly assignedOrders: ReadonlyArray<Order>;
  readonly calculateDistance?: Maybe<DistancePayload>;
  readonly checkOrderReview: OrderReviewCheckResponse;
  readonly dailyPaymentStatistics: ReadonlyArray<DailyPaymentStats>;
  readonly dailyStatistics: ReadonlyArray<DailyStatistic>;
  readonly defaultRegionHierarchy?: Maybe<RegionHierarchy>;
  readonly deliveringOrders: ReadonlyArray<Order>;
  readonly deliveryAddress?: Maybe<DeliveryAddress>;
  readonly deliveryAddresses: ReadonlyArray<DeliveryAddress>;
  readonly deliveryArea?: Maybe<DeliveryArea>;
  readonly deliveryAreas: ReadonlyArray<DeliveryArea>;
  readonly deliveryWorker?: Maybe<DeliveryWorker>;
  readonly deliveryWorkerPublicStatistics: Review;
  readonly deliveryWorkerRanking: ReadonlyArray<DeliveryWorkerRankingResponse>;
  readonly deliveryWorkerReviews: ReadonlyArray<Review>;
  readonly deliveryWorkerStatistics?: Maybe<DeliveryWorkerStatisticsResponse>;
  readonly deliveryWorkers: ReadonlyArray<DeliveryWorker>;
  readonly enabledDeliveryAreas: ReadonlyArray<DeliveryArea>;
  readonly favoriteProducts: FavoriteProductPage;
  readonly favoritesCount: Scalars['Long']['output'];
  readonly findUserByPhone?: Maybe<User>;
  readonly findUsersByAddress: ReadonlyArray<User>;
  readonly getDoNotDisturbSettings: DoNotDisturbSettings;
  readonly getMessageDetail?: Maybe<ClientMessage>;
  readonly getMessageHistory: MessageHistoryPage;
  readonly getMessageStatistics: MessageStatistics;
  readonly getMessageTypes: ReadonlyArray<MessageTypeInfo>;
  readonly getMessagesByType: MessageHistoryPage;
  readonly getRecentMessages: ReadonlyArray<ClientMessage>;
  readonly getSubscribedTopics: ReadonlyArray<Scalars['String']['output']>;
  readonly getUnreadMessageCount: Scalars['Int']['output'];
  readonly getUserNotificationSettings: UserNotificationSettings;
  readonly isInServiceArea?: Maybe<ServiceAreaPayload>;
  readonly isNotificationEnabled: Scalars['Boolean']['output'];
  readonly isProductFavorited: Scalars['Boolean']['output'];
  readonly isSubscribedToTopic: Scalars['Boolean']['output'];
  readonly lowStockProducts: ReadonlyArray<LowStockAlert>;
  readonly me?: Maybe<UserInfo>;
  readonly monthlyStatistics: ReadonlyArray<MonthlyStatistic>;
  readonly myAssignedOrders: ReadonlyArray<Order>;
  readonly myDeliveringOrders: ReadonlyArray<Order>;
  readonly myPaymentTransactions: ReadonlyArray<UserPaymentTransaction>;
  readonly myRefundRequests: ReadonlyArray<RefundRequest>;
  readonly myReviews: ReadonlyArray<Review>;
  readonly nearbyAddresses?: Maybe<NearbyAddressesPayload>;
  readonly onlineDeliveryWorkers: ReadonlyArray<DeliveryWorker>;
  readonly order?: Maybe<Order>;
  readonly orderByNumber?: Maybe<Order>;
  readonly orderPaymentInfo: OrderPaymentInfo;
  readonly orderStatistics: OrderStatistics;
  readonly ordersByStatus: ReadonlyArray<Order>;
  readonly ordersByUser: ReadonlyArray<Order>;
  readonly ordersByUserAndStatus: ReadonlyArray<Order>;
  readonly paymentMethodStatistics: ReadonlyArray<PaymentMethodStats>;
  readonly paymentPeriodStats: ReadonlyArray<PaymentPeriodStats>;
  readonly paymentStatistics?: Maybe<PaymentStatistics>;
  readonly paymentStatus: Scalars['String']['output'];
  readonly paymentTransaction?: Maybe<PaymentTransaction>;
  readonly paymentTransactions: ReadonlyArray<PaymentTransaction>;
  readonly pendingDeliveryOrders: ReadonlyArray<Order>;
  readonly product?: Maybe<Product>;
  readonly productStatistics?: Maybe<ProductStatistics>;
  readonly products: ProductPage;
  readonly productsByFavorites: ProductFavoritePage;
  readonly productsByMinSalesVolume: ReadonlyArray<Product>;
  readonly productsByPhRange: ReadonlyArray<Product>;
  readonly productsByTag: ReadonlyArray<Product>;
  readonly productsByWaterSource: ReadonlyArray<Product>;
  readonly productsPaginated?: Maybe<ProductPage>;
  readonly productsSortedBySalesVolume: ReadonlyArray<Product>;
  readonly productsSortedBySortOrder: ReadonlyArray<Product>;
  readonly refundEligibility: RefundEligibility;
  readonly refundRequest?: Maybe<RefundRequest>;
  readonly refundRequests: ReadonlyArray<RefundRequest>;
  readonly region?: Maybe<Region>;
  readonly regionByCoordinates?: Maybe<RegionCoordinatesPayload>;
  readonly regions: ReadonlyArray<Region>;
  readonly reviews: ReadonlyArray<Review>;
  readonly searchMessages: MessageHistoryPage;
  readonly searchRegions: ReadonlyArray<Region>;
  readonly specificationStatistics: Scalars['Map']['output'];
  readonly suspiciousTransactions: ReadonlyArray<SuspiciousTransaction>;
  readonly todayStatistics: TodayStatistics;
  readonly topSalesProducts: ReadonlyArray<Product>;
  readonly user?: Maybe<User>;
  readonly userAddresses: ReadonlyArray<Address>;
  readonly userDefaultAddress?: Maybe<Address>;
  readonly userPaymentTransactions: ReadonlyArray<PaymentTransaction>;
  readonly users: UserPage;
  readonly validateAddress: Scalars['Boolean']['output'];
  readonly waterSourceStatistics: Scalars['Map']['output'];
  readonly weeklyStatistics: ReadonlyArray<WeeklyStatistic>;
};


export type QueryActiveProductsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  sortBy?: InputMaybe<Scalars['String']['input']>;
  sortDirection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActiveProductsByStatusArgs = {
  status: ProductStatus;
};


export type QueryAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryAdminArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryAssignedOrdersArgs = {
  workerId: Scalars['PrimaryId']['input'];
};


export type QueryCalculateDistanceArgs = {
  lat1: Scalars['Float']['input'];
  lat2: Scalars['Float']['input'];
  lng1: Scalars['Float']['input'];
  lng2: Scalars['Float']['input'];
};


export type QueryCheckOrderReviewArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type QueryDailyPaymentStatisticsArgs = {
  dateFrom: Scalars['LocalDateTime']['input'];
  dateTo: Scalars['LocalDateTime']['input'];
};


export type QueryDailyStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryDeliveringOrdersArgs = {
  workerId: Scalars['PrimaryId']['input'];
};


export type QueryDeliveryAddressArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryDeliveryAreaArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryDeliveryWorkerArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryDeliveryWorkerPublicStatisticsArgs = {
  deliveryWorkerId: Scalars['PrimaryId']['input'];
};


export type QueryDeliveryWorkerRankingArgs = {
  minReviews?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  sortBy?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDeliveryWorkerReviewsArgs = {
  deliveryWorkerId: Scalars['PrimaryId']['input'];
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryDeliveryWorkerStatisticsArgs = {
  deliveryWorkerId: Scalars['PrimaryId']['input'];
};


export type QueryFavoriteProductsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryFindUserByPhoneArgs = {
  phone: Scalars['String']['input'];
};


export type QueryFindUsersByAddressArgs = {
  address: Scalars['String']['input'];
};


export type QueryGetMessageDetailArgs = {
  messageId: Scalars['PrimaryId']['input'];
};


export type QueryGetMessageHistoryArgs = {
  page?: InputMaybe<CustomPageRequest>;
};


export type QueryGetMessagesByTypeArgs = {
  messageType: Scalars['String']['input'];
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryGetRecentMessagesArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  messageType?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIsInServiceAreaArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type QueryIsNotificationEnabledArgs = {
  messageType: Scalars['String']['input'];
};


export type QueryIsProductFavoritedArgs = {
  productId: Scalars['PrimaryId']['input'];
};


export type QueryIsSubscribedToTopicArgs = {
  topic: Scalars['String']['input'];
};


export type QueryLowStockProductsArgs = {
  threshold?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMonthlyStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryMyPaymentTransactionsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMyRefundRequestsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMyReviewsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryNearbyAddressesArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
  radiusKm?: InputMaybe<Scalars['Float']['input']>;
};


export type QueryOrderArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type QueryOrderByNumberArgs = {
  orderNumber: Scalars['String']['input'];
};


export type QueryOrderPaymentInfoArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type QueryOrderStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryOrdersByStatusArgs = {
  status: OrderStatus;
};


export type QueryOrdersByUserArgs = {
  userId: Scalars['PrimaryId']['input'];
};


export type QueryOrdersByUserAndStatusArgs = {
  status: OrderStatus;
  userId: Scalars['PrimaryId']['input'];
};


export type QueryPaymentMethodStatisticsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
};


export type QueryPaymentPeriodStatsArgs = {
  from: Scalars['LocalDateTime']['input'];
  to: Scalars['LocalDateTime']['input'];
};


export type QueryPaymentStatisticsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
};


export type QueryPaymentStatusArgs = {
  transactionId: Scalars['String']['input'];
};


export type QueryPaymentTransactionArgs = {
  id: Scalars['String']['input'];
};


export type QueryPaymentTransactionsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  maxAmount?: InputMaybe<Scalars['BigDecimal']['input']>;
  minAmount?: InputMaybe<Scalars['BigDecimal']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<PaymentStatus>;
  userId?: InputMaybe<Scalars['Long']['input']>;
};


export type QueryProductArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryProductStatisticsArgs = {
  dateRange?: InputMaybe<DateRangeInput>;
};


export type QueryProductsArgs = {
  keyword?: InputMaybe<Scalars['String']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<ProductStatus>;
};


export type QueryProductsByFavoritesArgs = {
  minFavorites?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryProductsByMinSalesVolumeArgs = {
  minVolume: Scalars['Int']['input'];
};


export type QueryProductsByPhRangeArgs = {
  maxPh: Scalars['BigDecimal']['input'];
  minPh: Scalars['BigDecimal']['input'];
};


export type QueryProductsByTagArgs = {
  tag: Scalars['String']['input'];
};


export type QueryProductsByWaterSourceArgs = {
  waterSource: Scalars['String']['input'];
};


export type QueryProductsPaginatedArgs = {
  input?: InputMaybe<ProductListInput>;
};


export type QueryRefundEligibilityArgs = {
  orderId: Scalars['PrimaryId']['input'];
};


export type QueryRefundRequestArgs = {
  id: Scalars['String']['input'];
};


export type QueryRefundRequestsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<RefundStatus>;
};


export type QueryRegionArgs = {
  code: Scalars['String']['input'];
};


export type QueryRegionByCoordinatesArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type QueryRegionsArgs = {
  level?: InputMaybe<Scalars['Int']['input']>;
  parentCode?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  deliveryWorkerId?: InputMaybe<Scalars['Long']['input']>;
  maxRating?: InputMaybe<Scalars['Int']['input']>;
  minRating?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  userId?: InputMaybe<Scalars['Long']['input']>;
};


export type QuerySearchMessagesArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  keyword: Scalars['String']['input'];
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QuerySearchRegionsArgs = {
  keyword: Scalars['String']['input'];
  level?: InputMaybe<Scalars['Int']['input']>;
};


export type QuerySuspiciousTransactionsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryTopSalesProductsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryUserArgs = {
  id: Scalars['PrimaryId']['input'];
};


export type QueryUserAddressesArgs = {
  userId?: InputMaybe<Scalars['Long']['input']>;
};


export type QueryUserPaymentTransactionsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  userId: Scalars['PrimaryId']['input'];
};


export type QueryUsersArgs = {
  input?: InputMaybe<UserListInput>;
};


export type QueryValidateAddressArgs = {
  input: ValidateAddressInput;
};


export type QueryWeeklyStatisticsArgs = {
  input: DateRangeInput;
};

export type RefreshTokenInput = {
  readonly refreshToken: Scalars['String']['input'];
};

export enum RefundAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT'
}

export type RefundBucketDepositInput = {
  readonly depositId: Scalars['PrimaryId']['input'];
  readonly remark?: InputMaybe<Scalars['String']['input']>;
};

export type RefundEligibility = {
  readonly deadline?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly eligible: Scalars['Boolean']['output'];
  readonly orderAmount: Scalars['Money']['output'];
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly paidAmount: Scalars['Money']['output'];
  readonly refundPolicy?: Maybe<Scalars['String']['output']>;
  readonly refundReason?: Maybe<Scalars['String']['output']>;
  readonly refundableAmount: Scalars['Money']['output'];
};

export type RefundInput = {
  readonly refundAmount: Scalars['Money']['input'];
  readonly totalAmount: Scalars['Money']['input'];
  readonly transactionId: Scalars['String']['input'];
};

export type RefundRequest = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly id: Scalars['String']['output'];
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly originalTransactionId: Scalars['String']['output'];
  readonly processedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly processedBy?: Maybe<Scalars['Long']['output']>;
  readonly reason: Scalars['String']['output'];
  readonly requestedAt: Scalars['LocalDateTime']['output'];
  readonly status: RefundStatus;
  readonly userId: Scalars['PrimaryId']['output'];
};

export enum RefundStatus {
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED'
}

export type Region = {
  readonly code: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly level: Scalars['Int']['output'];
  readonly name: Scalars['String']['output'];
  readonly parentCode?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
};

export type RegionCoordinatesPayload = {
  readonly message: Scalars['String']['output'];
  readonly region?: Maybe<Region>;
  readonly success: Scalars['Boolean']['output'];
};

export type RegionHierarchy = {
  readonly cities: ReadonlyArray<Region>;
  readonly city: Region;
  readonly district: Region;
  readonly districts: ReadonlyArray<Region>;
  readonly province: Region;
  readonly provinces: ReadonlyArray<Region>;
};

export type RequestRefundInput = {
  readonly amount: Scalars['BigDecimal']['input'];
  readonly orderId: Scalars['PrimaryId']['input'];
  readonly outTradeNo: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
};

export type ReverseGeocodePayload = {
  readonly city?: Maybe<Scalars['String']['output']>;
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly confidence?: Maybe<Scalars['Float']['output']>;
  readonly district?: Maybe<Scalars['String']['output']>;
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly formattedAddress?: Maybe<Scalars['String']['output']>;
  readonly message: Scalars['String']['output'];
  readonly province?: Maybe<Scalars['String']['output']>;
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
  readonly street?: Maybe<Scalars['String']['output']>;
  readonly success: Scalars['Boolean']['output'];
};

export type Review = {
  readonly comment?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliveryWorkerId: Scalars['PrimaryId']['output'];
  readonly deliveryWorkerName?: Maybe<Scalars['String']['output']>;
  readonly isAnonymous: Scalars['Boolean']['output'];
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly rating: Scalars['Int']['output'];
  readonly reviewId: Scalars['PrimaryId']['output'];
  readonly userId?: Maybe<Scalars['PrimaryId']['output']>;
};

export type SalesReport = {
  readonly dateRange: DateRange;
  readonly salesBySpecification: ReadonlyArray<SpecificationStatistics>;
  readonly salesByWaterSource: ReadonlyArray<WaterSourceStatistics>;
  readonly topSellingProducts: ReadonlyArray<ProductSalesInfo>;
  readonly totalRevenue: Scalars['Money']['output'];
  readonly totalSales: Scalars['Int']['output'];
};

export enum SalesReportGroupBy {
  DAY = 'DAY',
  MONTH = 'MONTH',
  WEEK = 'WEEK'
}

export type SalesReportInput = {
  readonly dateRange: DateRangeInput;
  readonly groupBy?: SalesReportGroupBy;
  readonly includeSpecificationBreakdown?: Scalars['Boolean']['input'];
  readonly includeWaterSourceBreakdown?: Scalars['Boolean']['input'];
  readonly topProductLimit?: Scalars['Int']['input'];
};

export type ServiceAreaPayload = {
  readonly inServiceArea: Scalars['Boolean']['output'];
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type SpecificationStatistics = {
  readonly averagePrice: Scalars['Money']['output'];
  readonly productCount: Scalars['Int']['output'];
  readonly specification: Scalars['String']['output'];
  readonly totalSalesVolume: Scalars['Int']['output'];
};

export type StockAdjustmentInput = {
  readonly productId: Scalars['PrimaryId']['input'];
  readonly quantity: Scalars['Int']['input'];
  readonly reason?: InputMaybe<Scalars['String']['input']>;
  readonly type: StockAdjustmentType;
};

export type StockAdjustmentResult = {
  readonly message: Scalars['String']['output'];
  readonly newStock?: Maybe<Scalars['Int']['output']>;
  readonly previousStock?: Maybe<Scalars['Int']['output']>;
  readonly productId: Scalars['PrimaryId']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export enum StockAdjustmentType {
  DECREASE = 'DECREASE',
  INCREASE = 'INCREASE',
  SET = 'SET'
}

export type SuspiciousTransaction = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly frozenAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly frozenBy?: Maybe<Scalars['Long']['output']>;
  readonly id: Scalars['String']['output'];
  readonly isFrozen: Scalars['Boolean']['output'];
  readonly metadata?: Maybe<Scalars['Map']['output']>;
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly riskScore: Scalars['Float']['output'];
  readonly status: PaymentStatus;
  readonly suspiciousReason: Scalars['String']['output'];
  readonly transactionId?: Maybe<Scalars['String']['output']>;
  readonly userId: Scalars['PrimaryId']['output'];
};

export type TodayStatistics = {
  readonly completedOrders: Scalars['Int']['output'];
  readonly earningCents: Scalars['Long']['output'];
  readonly pendingOrders: Scalars['Int']['output'];
  readonly totalOrders: Scalars['Int']['output'];
};

export type UpdateAddressInput = {
  readonly city?: InputMaybe<Scalars['String']['input']>;
  readonly cityCode?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress?: InputMaybe<Scalars['String']['input']>;
  readonly district?: InputMaybe<Scalars['String']['input']>;
  readonly districtCode?: InputMaybe<Scalars['String']['input']>;
  readonly isDefault?: InputMaybe<Scalars['Boolean']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly province?: InputMaybe<Scalars['String']['input']>;
  readonly provinceCode?: InputMaybe<Scalars['String']['input']>;
  readonly receiverName?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateAdminInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly realName?: InputMaybe<Scalars['String']['input']>;
  readonly role?: InputMaybe<AdminRole>;
  readonly status?: InputMaybe<DeliveryWorkerStatus>;
  readonly username?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateDeliveryAddressInput = {
  readonly city?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress?: InputMaybe<Scalars['String']['input']>;
  readonly district?: InputMaybe<Scalars['String']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province?: InputMaybe<Scalars['String']['input']>;
  readonly receiverName?: InputMaybe<Scalars['String']['input']>;
  readonly receiverPhone?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateDeliveryWorkerInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly coordinates?: InputMaybe<Scalars['String']['input']>;
  readonly currentLocation?: InputMaybe<Scalars['String']['input']>;
  readonly earning?: InputMaybe<Scalars['Money']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly rating?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly wechatOpenId?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateNotificationSettingsInput = {
  readonly deliveryNotifications?: InputMaybe<Scalars['Boolean']['input']>;
  readonly orderUpdates?: InputMaybe<Scalars['Boolean']['input']>;
  readonly paymentNotifications?: InputMaybe<Scalars['Boolean']['input']>;
  readonly promotionalNotifications?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateProductInput = {
  readonly certificateImages?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly coverImageUrl?: InputMaybe<Scalars['String']['input']>;
  readonly deliverySettings?: InputMaybe<Scalars['JsonObject']['input']>;
  readonly depositPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly detailContent?: InputMaybe<Scalars['String']['input']>;
  readonly imageGallery?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly mineralContent?: InputMaybe<Scalars['String']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly originalPrice?: InputMaybe<Scalars['Money']['input']>;
  readonly price?: InputMaybe<Scalars['Money']['input']>;
  readonly salesVolume?: InputMaybe<Scalars['Int']['input']>;
  readonly sortOrder?: InputMaybe<Scalars['Int']['input']>;
  readonly specification?: InputMaybe<Scalars['String']['input']>;
  readonly status?: InputMaybe<ProductStatus>;
  readonly stock?: InputMaybe<Scalars['Int']['input']>;
  readonly subtitle?: InputMaybe<Scalars['String']['input']>;
  readonly tags?: InputMaybe<Scalars['JsonArray']['input']>;
  readonly waterSource?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileInput = {
  readonly avatar?: InputMaybe<Scalars['String']['input']>;
  readonly nickname?: InputMaybe<Scalars['String']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateRegionInput = {
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly parentCode?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateTransactionInput = {
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly freezeReason?: InputMaybe<Scalars['String']['input']>;
  readonly isFrozen?: InputMaybe<Scalars['Boolean']['input']>;
  readonly status?: InputMaybe<PaymentStatus>;
};

export type User = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly balanceCents: Scalars['Long']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly email: Scalars['String']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly nickname?: Maybe<Scalars['String']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly role: UserRole;
  readonly status: UserStatus;
  readonly totalSpentCents: Scalars['Long']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export enum UserEngagementLevel {
  HIGH = 'HIGH',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  VERY_HIGH = 'VERY_HIGH'
}

export type UserFavorite = {
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly product: Product;
  readonly user: User;
};

export type UserFavoriteAnalytics = {
  readonly activeUsersWithFavorites: Scalars['Long']['output'];
  readonly averageFavoritesPerUser: Scalars['Float']['output'];
  readonly newFavoritesThisMonth: Scalars['Long']['output'];
  readonly newFavoritesThisWeek: Scalars['Long']['output'];
  readonly newFavoritesToday: Scalars['Long']['output'];
  readonly totalFavorites: Scalars['Long']['output'];
};

export type UserFavoriteInsights = {
  readonly averageFavoritePrice: Scalars['Money']['output'];
  readonly engagementLevel: UserEngagementLevel;
  readonly favoriteCategories: ReadonlyArray<Scalars['String']['output']>;
  readonly favoriteToOrderRate: Scalars['Float']['output'];
  readonly lastActiveAt: Scalars['LocalDateTime']['output'];
  readonly totalFavorites: Scalars['Long']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
  readonly userNickname: Scalars['String']['output'];
};

export type UserFavoritePage = {
  readonly list: ReadonlyArray<UserFavorite>;
  readonly pageInfo: PageInfo;
};

export type UserFavoriteSummary = {
  readonly categories: ReadonlyArray<Scalars['String']['output']>;
  readonly favoriteCount: Scalars['Long']['output'];
  readonly lastFavoriteAdded?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly mostFavoritedCategory?: Maybe<Scalars['String']['output']>;
  readonly totalValueOfFavoritedProducts: Scalars['Money']['output'];
  readonly user: User;
};

export type UserFavoriteSummaryPage = {
  readonly list: ReadonlyArray<UserFavoriteSummary>;
  readonly pageInfo: PageInfo;
};

export type UserFavoriteWithProduct = {
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly product: Product;
  readonly productSalesVolume: Scalars['Int']['output'];
  readonly productStatus: ProductStatus;
  readonly productStock: Scalars['Int']['output'];
  readonly user: User;
};

export type UserFavoriteWithProductPage = {
  readonly list: ReadonlyArray<UserFavoriteWithProduct>;
  readonly pageInfo: PageInfo;
};

export type UserInfo = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly nickname?: Maybe<Scalars['String']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type UserListInput = {
  readonly page?: InputMaybe<Scalars['Int']['input']>;
  readonly search?: InputMaybe<Scalars['String']['input']>;
  readonly size?: InputMaybe<Scalars['Int']['input']>;
  readonly sort?: InputMaybe<Scalars['String']['input']>;
  readonly status?: InputMaybe<UserStatus>;
};

export type UserNotificationSettings = {
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliveryNotifications: Scalars['Boolean']['output'];
  readonly id: Scalars['PrimaryId']['output'];
  readonly orderUpdates: Scalars['Boolean']['output'];
  readonly paymentNotifications: Scalars['Boolean']['output'];
  readonly promotionalNotifications: Scalars['Boolean']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['PrimaryId']['output'];
};

export type UserPage = {
  readonly list: ReadonlyArray<User>;
  readonly pageInfo: PageInfo;
};

export type UserPaymentTransaction = {
  readonly amount: Scalars['BigDecimal']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['String']['output'];
  readonly orderId: Scalars['PrimaryId']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly refundAmount?: Maybe<Scalars['BigDecimal']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
};

export enum UserRole {
  ADMIN = 'ADMIN',
  NONE = 'NONE',
  USER = 'USER',
  WORKER = 'WORKER'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED'
}

export type ValidateAddressInput = {
  readonly city: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type WaterSourceStatistics = {
  readonly averagePrice: Scalars['Money']['output'];
  readonly productCount: Scalars['Int']['output'];
  readonly totalSalesVolume: Scalars['Int']['output'];
  readonly waterSource: Scalars['String']['output'];
};

export type WeChatLoginResponse = {
  readonly accessToken: Scalars['String']['output'];
  readonly expiresIn: Scalars['Int']['output'];
  readonly refreshToken: Scalars['String']['output'];
  readonly userInfo: UserInfo;
};

export type WeChatTokenResponse = {
  readonly accessToken: Scalars['String']['output'];
  readonly expiresIn: Scalars['Int']['output'];
  readonly refreshToken: Scalars['String']['output'];
};

export type WechatCallbackInput = {
  readonly appId?: InputMaybe<Scalars['String']['input']>;
  readonly mchId?: InputMaybe<Scalars['String']['input']>;
  readonly outTradeNo?: InputMaybe<Scalars['String']['input']>;
  readonly resource: Scalars['String']['input'];
  readonly resourceType: Scalars['String']['input'];
  readonly summary: Scalars['String']['input'];
  readonly transactionId?: InputMaybe<Scalars['String']['input']>;
};

export type WechatLoginInput = {
  readonly code: Scalars['String']['input'];
};

export type WeeklyStatistic = {
  readonly endDate: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
  readonly startDate: Scalars['String']['output'];
  readonly weekNumber: Scalars['Int']['output'];
  readonly year: Scalars['Int']['output'];
};
