# Address management (for admin)

extend type Query {
  # Address queries
  userAddresses(userId: Long): [Address!]!
  addresses: [Address!]!
  address(id: PrimaryId!): Address
  searchUserAddresses(keyword: String!, userId: Long, page: Int = 0, size: Int = 10): [Address!]!
  searchAllAddresses(keyword: String, page: Int = 0, size: Int = 10): [Address!]!
}

extend type Mutation {
  # Address mutations
  createAdminAddress(input: AddressInput!): Address!
  batchImportAddresses(input: [AddressInput!]!): BatchImportAddressesResult!
  deleteAdminAddress(id: PrimaryId!): Boolean!
}
