// Generated by GraphQL Code Generator - DO NOT EDIT
export type Maybe<T> = T | null | undefined;
export type InputMaybe<T> = T | null | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  BigDecimal: { input: number; output: number; }
  LocalDateTime: { input: string; output: string; }
  Long: { input: number; output: number; }
  Map: { input: { [key: string]: any }; output: { [key: string]: any }; }
  Money: { input: number; output: number; }
};

export type Address = {
  readonly city: Scalars['String']['output'];
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['Long']['output'];
  readonly isDefault: Scalars['Boolean']['output'];
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly phone: Scalars['String']['output'];
  readonly province: Scalars['String']['output'];
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
  readonly receiverName: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['Long']['output'];
};

export type AddressInput = {
  readonly city: Scalars['String']['input'];
  readonly cityCode: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly districtCode: Scalars['String']['input'];
  readonly isDefault?: Scalars['Boolean']['input'];
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly phone: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
  readonly provinceCode: Scalars['String']['input'];
  readonly receiverName: Scalars['String']['input'];
};

export type AddressValidationInput = {
  readonly city: Scalars['String']['input'];
  readonly cityCode?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly districtCode?: InputMaybe<Scalars['String']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province: Scalars['String']['input'];
  readonly provinceCode?: InputMaybe<Scalars['String']['input']>;
};

export type AddressValidationPayload = {
  readonly coordinatesValid: Scalars['Boolean']['output'];
  readonly errors: ReadonlyArray<Scalars['String']['output']>;
  readonly isDuplicate: Scalars['Boolean']['output'];
  readonly isValid: Scalars['Boolean']['output'];
  readonly message: Scalars['String']['output'];
  readonly normalizedAddress?: Maybe<NormalizedAddress>;
  readonly success: Scalars['Boolean']['output'];
};

export type Admin = {
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['Long']['output'];
  readonly lastLoginAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly realName?: Maybe<Scalars['String']['output']>;
  readonly role: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly username: Scalars['String']['output'];
};

export type AuthPayload = {
  readonly accessToken: Scalars['String']['output'];
  readonly refreshToken: Scalars['String']['output'];
  readonly user: User;
};

export type BooleanPayload = {
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type CreateDeliveryAddressInput = {
  readonly city: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province: Scalars['String']['input'];
  readonly receiverName: Scalars['String']['input'];
  readonly receiverPhone: Scalars['String']['input'];
};

export type CreateDeliveryAreaInput = {
  readonly city: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly enabled?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type CreateDeliveryWorkerInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly coordinates?: InputMaybe<Scalars['String']['input']>;
  readonly currentLocation?: InputMaybe<Scalars['String']['input']>;
  readonly earning?: InputMaybe<Scalars['Money']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name: Scalars['String']['input'];
  readonly phone: Scalars['String']['input'];
  readonly rating?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly wechatOpenId: Scalars['String']['input'];
};

export type CreateManualRefundInput = {
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly amount: Scalars['Money']['input'];
  readonly orderId: Scalars['Long']['input'];
  readonly originalTransactionId: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
  readonly userId: Scalars['Long']['input'];
};

export type CreateOrderInput = {
  readonly addressId: Scalars['Long']['input'];
  readonly productId: Scalars['Long']['input'];
  readonly quantity: Scalars['Int']['input'];
};

export type CreateProductInput = {
  readonly coverImageUrl: Scalars['String']['input'];
  readonly description?: InputMaybe<Scalars['String']['input']>;
  readonly detailImages?: InputMaybe<Scalars['String']['input']>;
  readonly name: Scalars['String']['input'];
  readonly price: Scalars['Money']['input'];
  readonly stock: Scalars['Int']['input'];
};

export type CreateRegionInput = {
  readonly code: Scalars['String']['input'];
  readonly level: Scalars['Int']['input'];
  readonly name: Scalars['String']['input'];
  readonly parentCode?: InputMaybe<Scalars['String']['input']>;
};

export type CreateReviewRequest = {
  readonly comment?: InputMaybe<Scalars['String']['input']>;
  readonly deliveryWorkerId: Scalars['Long']['input'];
  readonly isAnonymous?: InputMaybe<Scalars['Boolean']['input']>;
  readonly orderId: Scalars['Long']['input'];
  readonly rating: Scalars['Int']['input'];
};

export type CreateWechatPaymentInput = {
  readonly amount: Scalars['Money']['input'];
  readonly description: Scalars['String']['input'];
  readonly orderId: Scalars['Long']['input'];
};

export type DailyPaymentStats = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly date: Scalars['String']['output'];
  readonly failedTransactions: Scalars['Long']['output'];
  readonly paymentMethodBreakdown: ReadonlyArray<PaymentMethodStats>;
  readonly peakHour: Scalars['Int']['output'];
  readonly refundCount: Scalars['Long']['output'];
  readonly refundedAmount: Scalars['Money']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export type DailyStatistic = {
  readonly date: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
};

export type DateRange = {
  readonly endDate: Scalars['LocalDateTime']['output'];
  readonly startDate: Scalars['LocalDateTime']['output'];
};

export type DateRangeInput = {
  readonly endDate: Scalars['LocalDateTime']['input'];
  readonly startDate: Scalars['LocalDateTime']['input'];
};

export type DeliveryAddress = {
  readonly city: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly id: Scalars['Long']['output'];
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly province: Scalars['String']['output'];
  readonly receiverName: Scalars['String']['output'];
  readonly receiverPhone: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['Long']['output'];
};

export type DeliveryArea = {
  readonly city: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly enabled: Scalars['Boolean']['output'];
  readonly id: Scalars['Long']['output'];
  readonly name: Scalars['String']['output'];
  readonly province: Scalars['String']['output'];
};

export type DeliveryWorker = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly averageRating?: Maybe<Scalars['BigDecimal']['output']>;
  readonly completedOrders: Scalars['Int']['output'];
  readonly coordinates?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly currentLocation?: Maybe<Scalars['String']['output']>;
  readonly earning?: Maybe<Scalars['Money']['output']>;
  readonly id: Scalars['Long']['output'];
  readonly isAvailable: Scalars['Boolean']['output'];
  readonly name: Scalars['String']['output'];
  readonly onlineStatus: DeliveryWorkerStatus;
  readonly phone: Scalars['String']['output'];
  readonly rating?: Maybe<Scalars['BigDecimal']['output']>;
  readonly totalOrders: Scalars['Int']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['Long']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type DeliveryWorkerRankingResponse = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly positiveRatingPercentage: Scalars['Float']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly workerId: Scalars['Long']['output'];
  readonly workerName?: Maybe<Scalars['String']['output']>;
};

export type DeliveryWorkerStatistics = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly deliveryWorkerId: Scalars['Long']['output'];
  readonly fiveStarReviews: Scalars['Long']['output'];
  readonly fourStarReviews: Scalars['Long']['output'];
  readonly oneStarReviews: Scalars['Long']['output'];
  readonly threeStarReviews: Scalars['Long']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly twoStarReviews: Scalars['Long']['output'];
};

export type DeliveryWorkerStatisticsResponse = {
  readonly averageRating: Scalars['BigDecimal']['output'];
  readonly deliveryWorkerId: Scalars['Long']['output'];
  readonly fiveStarReviews: Scalars['Long']['output'];
  readonly fourStarReviews: Scalars['Long']['output'];
  readonly lastUpdated: Scalars['LocalDateTime']['output'];
  readonly oneStarReviews: Scalars['Long']['output'];
  readonly ratingDistribution: Scalars['Map']['output'];
  readonly threeStarReviews: Scalars['Long']['output'];
  readonly totalReviews: Scalars['Long']['output'];
  readonly twoStarReviews: Scalars['Long']['output'];
  readonly workerName?: Maybe<Scalars['String']['output']>;
};

export enum DeliveryWorkerStatus {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE'
}

export type DistancePayload = {
  readonly distanceKm?: Maybe<Scalars['Float']['output']>;
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type ExportTransactionsInput = {
  readonly dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  readonly format?: Scalars['String']['input'];
  readonly includeMetadata?: Scalars['Boolean']['input'];
  readonly maxAmount?: InputMaybe<Scalars['Money']['input']>;
  readonly minAmount?: InputMaybe<Scalars['Money']['input']>;
  readonly paymentMethod?: InputMaybe<PaymentMethod>;
  readonly status?: InputMaybe<PaymentStatus>;
  readonly userId?: InputMaybe<Scalars['Long']['input']>;
};

export type GeocodeInput = {
  readonly city: Scalars['String']['input'];
  readonly detailAddress: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type GeocodePayload = {
  readonly latitude?: Maybe<Scalars['Float']['output']>;
  readonly longitude?: Maybe<Scalars['Float']['output']>;
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type MonthlyStatistic = {
  readonly month: Scalars['Int']['output'];
  readonly monthName: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
  readonly year: Scalars['Int']['output'];
};

export type Mutation = {
  readonly cancelOrder: Order;
  readonly createAddress: Address;
  readonly createDeliveryAddress: DeliveryAddress;
  readonly createDeliveryArea: DeliveryArea;
  readonly createDeliveryWorker: DeliveryWorker;
  readonly createManualRefund: RefundRequest;
  readonly createOrder: Order;
  readonly createProduct: Product;
  readonly createRegion: Region;
  readonly createReview: Review;
  readonly createWechatPayment: PaymentData;
  readonly decreaseStock: Scalars['Boolean']['output'];
  readonly deleteAddress: Scalars['Boolean']['output'];
  readonly deleteDeliveryAddress: Scalars['Boolean']['output'];
  readonly deleteDeliveryArea: Scalars['Boolean']['output'];
  readonly deleteDeliveryWorker: Scalars['Boolean']['output'];
  readonly deleteProduct: Scalars['Boolean']['output'];
  readonly deleteRegion: Scalars['Boolean']['output'];
  readonly exportTransactions: Scalars['String']['output'];
  readonly forceCompletePayment: Scalars['Boolean']['output'];
  readonly forceRefund: Scalars['Boolean']['output'];
  readonly freezeSuspiciousTransaction: Scalars['Boolean']['output'];
  readonly geocodeAddress: GeocodePayload;
  readonly handleWechatCallback: Scalars['String']['output'];
  readonly increaseStock: Scalars['String']['output'];
  readonly logout: Scalars['Boolean']['output'];
  readonly processRefund: RefundRequest;
  readonly processSuspiciousTransaction: SuspiciousTransaction;
  readonly refreshToken: WeChatTokenResponse;
  readonly refund: Scalars['Boolean']['output'];
  readonly requestRefund: RefundRequest;
  readonly reverseGeocode: ReverseGeocodePayload;
  readonly setDefaultAddress: Scalars['Boolean']['output'];
  readonly setDefaultDeliveryAddress: Scalars['Boolean']['output'];
  readonly updateAddress: Address;
  readonly updateDeliveryAddress: DeliveryAddress;
  readonly updateDeliveryArea: DeliveryArea;
  readonly updateDeliveryWorker: DeliveryWorker;
  readonly updateOrderStatus: Order;
  readonly updateProduct: Product;
  readonly updateProfile: UserInfo;
  readonly updateRegion: Region;
  readonly updateTransaction: PaymentTransaction;
  readonly updateTransactionNote: Scalars['Boolean']['output'];
  readonly updateWorkerStatus: DeliveryWorker;
  readonly validateAddress: AddressValidationPayload;
  readonly wechatLogin: WeChatLoginResponse;
};


export type MutationCancelOrderArgs = {
  orderId: Scalars['Long']['input'];
};


export type MutationCreateAddressArgs = {
  input: AddressInput;
};


export type MutationCreateDeliveryAddressArgs = {
  input: CreateDeliveryAddressInput;
};


export type MutationCreateDeliveryAreaArgs = {
  input: CreateDeliveryAreaInput;
};


export type MutationCreateDeliveryWorkerArgs = {
  input: CreateDeliveryWorkerInput;
};


export type MutationCreateManualRefundArgs = {
  input: CreateManualRefundInput;
};


export type MutationCreateOrderArgs = {
  input: CreateOrderInput;
};


export type MutationCreateProductArgs = {
  input: CreateProductInput;
};


export type MutationCreateRegionArgs = {
  input: CreateRegionInput;
};


export type MutationCreateReviewArgs = {
  input: CreateReviewRequest;
};


export type MutationCreateWechatPaymentArgs = {
  input: CreateWechatPaymentInput;
};


export type MutationDecreaseStockArgs = {
  productId: Scalars['Long']['input'];
  quantity: Scalars['Int']['input'];
};


export type MutationDeleteAddressArgs = {
  id: Scalars['Long']['input'];
};


export type MutationDeleteDeliveryAddressArgs = {
  id: Scalars['Long']['input'];
};


export type MutationDeleteDeliveryAreaArgs = {
  id: Scalars['Long']['input'];
};


export type MutationDeleteDeliveryWorkerArgs = {
  workerId: Scalars['Long']['input'];
};


export type MutationDeleteProductArgs = {
  id: Scalars['Long']['input'];
};


export type MutationDeleteRegionArgs = {
  code: Scalars['String']['input'];
};


export type MutationExportTransactionsArgs = {
  input: ExportTransactionsInput;
};


export type MutationForceCompletePaymentArgs = {
  adminNote: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationForceRefundArgs = {
  adminNote: Scalars['String']['input'];
  amount: Scalars['BigDecimal']['input'];
  reason: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationFreezeSuspiciousTransactionArgs = {
  reason: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationGeocodeAddressArgs = {
  address: GeocodeInput;
};


export type MutationHandleWechatCallbackArgs = {
  input: WechatCallbackInput;
};


export type MutationIncreaseStockArgs = {
  productId: Scalars['Long']['input'];
  quantity: Scalars['Int']['input'];
};


export type MutationProcessRefundArgs = {
  input: ProcessRefundInput;
};


export type MutationProcessSuspiciousTransactionArgs = {
  input: ProcessSuspiciousTransactionInput;
};


export type MutationRefreshTokenArgs = {
  input: RefreshTokenInput;
};


export type MutationRefundArgs = {
  input: RefundInput;
};


export type MutationRequestRefundArgs = {
  input: RequestRefundInput;
};


export type MutationReverseGeocodeArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type MutationSetDefaultAddressArgs = {
  id: Scalars['Long']['input'];
};


export type MutationSetDefaultDeliveryAddressArgs = {
  id: Scalars['Long']['input'];
};


export type MutationUpdateAddressArgs = {
  id: Scalars['Long']['input'];
  input: UpdateAddressInput;
};


export type MutationUpdateDeliveryAddressArgs = {
  id: Scalars['Long']['input'];
  input: UpdateDeliveryAddressInput;
};


export type MutationUpdateDeliveryAreaArgs = {
  id: Scalars['Long']['input'];
  input: CreateDeliveryAreaInput;
};


export type MutationUpdateDeliveryWorkerArgs = {
  input: UpdateDeliveryWorkerInput;
  workerId: Scalars['Long']['input'];
};


export type MutationUpdateOrderStatusArgs = {
  orderId: Scalars['Long']['input'];
  status: OrderStatus;
};


export type MutationUpdateProductArgs = {
  id: Scalars['Long']['input'];
  input: UpdateProductInput;
};


export type MutationUpdateProfileArgs = {
  input: UpdateProfileInput;
};


export type MutationUpdateRegionArgs = {
  code: Scalars['String']['input'];
  input: UpdateRegionInput;
};


export type MutationUpdateTransactionArgs = {
  input: UpdateTransactionInput;
  transactionId: Scalars['String']['input'];
};


export type MutationUpdateTransactionNoteArgs = {
  note: Scalars['String']['input'];
  transactionId: Scalars['String']['input'];
};


export type MutationUpdateWorkerStatusArgs = {
  status: DeliveryWorkerStatus;
  workerId: Scalars['Long']['input'];
};


export type MutationValidateAddressArgs = {
  input: AddressValidationInput;
};


export type MutationWechatLoginArgs = {
  input: WechatLoginInput;
};

export type NearbyAddressesPayload = {
  readonly addresses: ReadonlyArray<Address>;
  readonly distanceMap: Scalars['Map']['output'];
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type NormalizedAddress = {
  readonly city: Scalars['String']['output'];
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly detailAddress: Scalars['String']['output'];
  readonly district: Scalars['String']['output'];
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly province: Scalars['String']['output'];
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
};

export type Order = {
  readonly address: Address;
  readonly amount: Scalars['Money']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliveryPhotos?: Maybe<ReadonlyArray<Scalars['String']['output']>>;
  readonly deliveryWorker?: Maybe<DeliveryWorker>;
  readonly id: Scalars['Long']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paymentMethod?: Maybe<Scalars['String']['output']>;
  readonly paymentTime?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly paymentTransactionId?: Maybe<Scalars['String']['output']>;
  readonly product: Product;
  readonly quantity: Scalars['Int']['output'];
  readonly status: OrderStatus;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly user: User;
};

export type OrderPaymentInfo = {
  readonly amount: Scalars['Money']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly orderId: Scalars['Long']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paidAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly paymentMethod: PaymentMethod;
  readonly refundAmount?: Maybe<Scalars['Money']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
};

export type OrderReviewCheckResponse = {
  readonly canReview: Scalars['Boolean']['output'];
  readonly hasReviewed: Scalars['Boolean']['output'];
  readonly review?: Maybe<Review>;
};

export type OrderStatistics = {
  readonly averageOrderValue: Scalars['Money']['output'];
  readonly dateRange: DateRange;
  readonly totalOrders: Scalars['Int']['output'];
  readonly totalRevenue: Scalars['Money']['output'];
};

export enum OrderStatus {
  CANCELLED = 'CANCELLED',
  CONFIRMED = 'CONFIRMED',
  DELIVERED = 'DELIVERED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  REFUNDED = 'REFUNDED'
}

export type PaymentData = {
  readonly appId: Scalars['String']['output'];
  readonly codeUrl: Scalars['String']['output'];
  readonly nonceStr: Scalars['String']['output'];
  readonly outTradeNo: Scalars['String']['output'];
  readonly packageValue: Scalars['String']['output'];
  readonly paySign: Scalars['String']['output'];
  readonly signType: Scalars['String']['output'];
  readonly timeStamp: Scalars['String']['output'];
};

export enum PaymentMethod {
  ALIPAY = 'ALIPAY',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  WECHAT_PAY = 'WECHAT_PAY'
}

export type PaymentMethodStats = {
  readonly averageAmount: Scalars['Money']['output'];
  readonly failureCount: Scalars['Long']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly refundCount: Scalars['Long']['output'];
  readonly successCount: Scalars['Long']['output'];
  readonly successRate: Scalars['Float']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly transactionCount: Scalars['Long']['output'];
};

export type PaymentPeriodStats = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly failedTransactions: Scalars['Long']['output'];
  readonly paymentMethodBreakdown: ReadonlyArray<PaymentMethodStats>;
  readonly period: Scalars['String']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export type PaymentStatistics = {
  readonly averageTransactionAmount: Scalars['Money']['output'];
  readonly dailyStats: ReadonlyArray<DailyPaymentStats>;
  readonly failedTransactions: Scalars['Long']['output'];
  readonly refundCount: Scalars['Long']['output'];
  readonly refundedAmount: Scalars['Money']['output'];
  readonly successfulTransactions: Scalars['Long']['output'];
  readonly totalAmount: Scalars['Money']['output'];
  readonly totalTransactions: Scalars['Long']['output'];
};

export enum PaymentStatus {
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  REFUNDED = 'REFUNDED',
  SUCCESS = 'SUCCESS'
}

export type PaymentStatusInfo = {
  readonly amount: Scalars['BigDecimal']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly orderNumber: Scalars['String']['output'];
  readonly paidAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly refundAmount?: Maybe<Scalars['BigDecimal']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId: Scalars['String']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
};

export type PaymentTransaction = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly externalTransactionId?: Maybe<Scalars['String']['output']>;
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly gateway: Scalars['String']['output'];
  readonly id: Scalars['String']['output'];
  readonly metadata?: Maybe<Scalars['Map']['output']>;
  readonly orderId: Scalars['Long']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly userId: Scalars['Long']['output'];
};

export type ProcessRefundInput = {
  readonly action: RefundAction;
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly amount: Scalars['Money']['input'];
  readonly orderId: Scalars['Long']['input'];
  readonly originalTransactionId: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
  readonly refundRequestId: Scalars['String']['input'];
  readonly userId: Scalars['Long']['input'];
};

export type ProcessSuspiciousTransactionInput = {
  readonly action: Scalars['String']['input'];
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly transactionId: Scalars['String']['input'];
};

export type Product = {
  readonly coverImageUrl: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly description?: Maybe<Scalars['String']['output']>;
  readonly detailImages?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['Long']['output'];
  readonly name: Scalars['String']['output'];
  readonly price: Scalars['Money']['output'];
  readonly status: ProductStatus;
  readonly stock: Scalars['Int']['output'];
  readonly updatedAt: Scalars['LocalDateTime']['output'];
};

export enum ProductStatus {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE'
}

export type Query = {
  readonly activeProducts: ReadonlyArray<Product>;
  readonly address?: Maybe<Address>;
  readonly addresses: ReadonlyArray<Address>;
  readonly admin?: Maybe<Admin>;
  readonly admins: ReadonlyArray<Admin>;
  readonly calculateDistance?: Maybe<DistancePayload>;
  readonly checkOrderReview: OrderReviewCheckResponse;
  readonly dailyPaymentStatistics: ReadonlyArray<DailyPaymentStats>;
  readonly dailyStatistics: ReadonlyArray<DailyStatistic>;
  readonly defaultRegionHierarchy?: Maybe<RegionHierarchy>;
  readonly deliveryAddress?: Maybe<DeliveryAddress>;
  readonly deliveryAddresses: ReadonlyArray<DeliveryAddress>;
  readonly deliveryArea?: Maybe<DeliveryArea>;
  readonly deliveryAreas: ReadonlyArray<DeliveryArea>;
  readonly deliveryWorker?: Maybe<DeliveryWorker>;
  readonly deliveryWorkerPublicStatistics: Review;
  readonly deliveryWorkerRanking: ReadonlyArray<DeliveryWorkerRankingResponse>;
  readonly deliveryWorkerReviews: ReadonlyArray<Review>;
  readonly deliveryWorkerStatistics: DeliveryWorkerStatisticsResponse;
  readonly deliveryWorkers: ReadonlyArray<DeliveryWorker>;
  readonly enabledDeliveryAreas: ReadonlyArray<DeliveryArea>;
  readonly isInServiceArea?: Maybe<ServiceAreaPayload>;
  readonly me?: Maybe<UserInfo>;
  readonly monthlyStatistics: ReadonlyArray<MonthlyStatistic>;
  readonly myPaymentTransactions: ReadonlyArray<UserPaymentTransaction>;
  readonly myRefundRequests: ReadonlyArray<RefundRequest>;
  readonly myReviews: ReadonlyArray<Review>;
  readonly nearbyAddresses?: Maybe<NearbyAddressesPayload>;
  readonly onlineDeliveryWorkers: ReadonlyArray<DeliveryWorker>;
  readonly order?: Maybe<Order>;
  readonly orderByNumber?: Maybe<Order>;
  readonly orderPaymentInfo: OrderPaymentInfo;
  readonly orderStatistics: OrderStatistics;
  readonly ordersByStatus: ReadonlyArray<Order>;
  readonly ordersByUser: ReadonlyArray<Order>;
  readonly ordersByUserAndStatus: ReadonlyArray<Order>;
  readonly paymentMethodStatistics: ReadonlyArray<PaymentMethodStats>;
  readonly paymentPeriodStats: ReadonlyArray<PaymentPeriodStats>;
  readonly paymentStatistics?: Maybe<PaymentStatistics>;
  readonly paymentStatus: Scalars['String']['output'];
  readonly paymentTransaction?: Maybe<PaymentTransaction>;
  readonly paymentTransactions: ReadonlyArray<PaymentTransaction>;
  readonly product?: Maybe<Product>;
  readonly products: ReadonlyArray<Product>;
  readonly refundEligibility: RefundEligibility;
  readonly refundRequest?: Maybe<RefundRequest>;
  readonly refundRequests: ReadonlyArray<RefundRequest>;
  readonly region?: Maybe<Region>;
  readonly regionByCoordinates?: Maybe<RegionCoordinatesPayload>;
  readonly regions: ReadonlyArray<Region>;
  readonly reviews: ReadonlyArray<Review>;
  readonly searchRegions: ReadonlyArray<Region>;
  readonly suspiciousTransactions: ReadonlyArray<SuspiciousTransaction>;
  readonly user?: Maybe<User>;
  readonly userAddresses: ReadonlyArray<Address>;
  readonly userDefaultAddress?: Maybe<Address>;
  readonly userPaymentTransactions: ReadonlyArray<PaymentTransaction>;
  readonly users: UserListResponse;
  readonly validateAddress: Scalars['Boolean']['output'];
  readonly weeklyStatistics: ReadonlyArray<WeeklyStatistic>;
};


export type QueryAddressArgs = {
  id: Scalars['Long']['input'];
};


export type QueryAdminArgs = {
  id: Scalars['Long']['input'];
};


export type QueryCalculateDistanceArgs = {
  lat1: Scalars['Float']['input'];
  lat2: Scalars['Float']['input'];
  lng1: Scalars['Float']['input'];
  lng2: Scalars['Float']['input'];
};


export type QueryCheckOrderReviewArgs = {
  orderId: Scalars['Long']['input'];
};


export type QueryDailyPaymentStatisticsArgs = {
  dateFrom: Scalars['LocalDateTime']['input'];
  dateTo: Scalars['LocalDateTime']['input'];
};


export type QueryDailyStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryDeliveryAddressArgs = {
  id: Scalars['Long']['input'];
};


export type QueryDeliveryAreaArgs = {
  id: Scalars['Long']['input'];
};


export type QueryDeliveryWorkerArgs = {
  id: Scalars['Long']['input'];
};


export type QueryDeliveryWorkerPublicStatisticsArgs = {
  deliveryWorkerId: Scalars['Long']['input'];
};


export type QueryDeliveryWorkerRankingArgs = {
  minReviews?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  sortBy?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDeliveryWorkerReviewsArgs = {
  deliveryWorkerId: Scalars['Long']['input'];
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryDeliveryWorkerStatisticsArgs = {
  deliveryWorkerId: Scalars['Long']['input'];
};


export type QueryIsInServiceAreaArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type QueryMonthlyStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryMyPaymentTransactionsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMyRefundRequestsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMyReviewsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryNearbyAddressesArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
  radiusKm?: InputMaybe<Scalars['Float']['input']>;
};


export type QueryOrderArgs = {
  orderId: Scalars['Long']['input'];
};


export type QueryOrderByNumberArgs = {
  orderNumber: Scalars['String']['input'];
};


export type QueryOrderPaymentInfoArgs = {
  orderId: Scalars['Long']['input'];
};


export type QueryOrderStatisticsArgs = {
  input: DateRangeInput;
};


export type QueryOrdersByStatusArgs = {
  status: OrderStatus;
};


export type QueryOrdersByUserArgs = {
  userId: Scalars['Long']['input'];
};


export type QueryOrdersByUserAndStatusArgs = {
  status: OrderStatus;
  userId: Scalars['Long']['input'];
};


export type QueryPaymentMethodStatisticsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
};


export type QueryPaymentPeriodStatsArgs = {
  from: Scalars['LocalDateTime']['input'];
  to: Scalars['LocalDateTime']['input'];
};


export type QueryPaymentStatisticsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
};


export type QueryPaymentStatusArgs = {
  transactionId: Scalars['String']['input'];
};


export type QueryPaymentTransactionArgs = {
  id: Scalars['String']['input'];
};


export type QueryPaymentTransactionsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  maxAmount?: InputMaybe<Scalars['BigDecimal']['input']>;
  minAmount?: InputMaybe<Scalars['BigDecimal']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<PaymentStatus>;
  userId?: InputMaybe<Scalars['Long']['input']>;
};


export type QueryProductArgs = {
  id: Scalars['Long']['input'];
};


export type QueryRefundEligibilityArgs = {
  orderId: Scalars['Long']['input'];
};


export type QueryRefundRequestArgs = {
  id: Scalars['String']['input'];
};


export type QueryRefundRequestsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  status?: InputMaybe<RefundStatus>;
};


export type QueryRegionArgs = {
  code: Scalars['String']['input'];
};


export type QueryRegionByCoordinatesArgs = {
  latitude: Scalars['Float']['input'];
  longitude: Scalars['Float']['input'];
};


export type QueryRegionsArgs = {
  level?: InputMaybe<Scalars['Int']['input']>;
  parentCode?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  deliveryWorkerId?: InputMaybe<Scalars['Long']['input']>;
  maxRating?: InputMaybe<Scalars['Int']['input']>;
  minRating?: InputMaybe<Scalars['Int']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  userId?: InputMaybe<Scalars['Long']['input']>;
};


export type QuerySearchRegionsArgs = {
  keyword: Scalars['String']['input'];
  level?: InputMaybe<Scalars['Int']['input']>;
};


export type QuerySuspiciousTransactionsArgs = {
  dateFrom?: InputMaybe<Scalars['LocalDateTime']['input']>;
  dateTo?: InputMaybe<Scalars['LocalDateTime']['input']>;
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryUserArgs = {
  id: Scalars['Long']['input'];
};


export type QueryUserPaymentTransactionsArgs = {
  page?: InputMaybe<Scalars['Int']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  userId: Scalars['Long']['input'];
};


export type QueryUsersArgs = {
  input?: InputMaybe<UserListInput>;
};


export type QueryValidateAddressArgs = {
  input: ValidateAddressInput;
};


export type QueryWeeklyStatisticsArgs = {
  input: DateRangeInput;
};

export type RefreshTokenInput = {
  readonly refreshToken: Scalars['String']['input'];
};

export enum RefundAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT'
}

export type RefundEligibility = {
  readonly deadline?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly eligible: Scalars['Boolean']['output'];
  readonly orderAmount: Scalars['Money']['output'];
  readonly orderId: Scalars['Long']['output'];
  readonly paidAmount: Scalars['Money']['output'];
  readonly refundPolicy?: Maybe<Scalars['String']['output']>;
  readonly refundReason?: Maybe<Scalars['String']['output']>;
  readonly refundableAmount: Scalars['Money']['output'];
};

export type RefundInput = {
  readonly refundAmount: Scalars['Money']['input'];
  readonly totalAmount: Scalars['Money']['input'];
  readonly transactionId: Scalars['String']['input'];
};

export type RefundRequest = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly id: Scalars['String']['output'];
  readonly orderId: Scalars['Long']['output'];
  readonly originalTransactionId: Scalars['String']['output'];
  readonly processedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly processedBy?: Maybe<Scalars['Long']['output']>;
  readonly reason: Scalars['String']['output'];
  readonly requestedAt: Scalars['LocalDateTime']['output'];
  readonly status: RefundStatus;
  readonly userId: Scalars['Long']['output'];
};

export enum RefundStatus {
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED'
}

export type Region = {
  readonly code: Scalars['String']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['Long']['output'];
  readonly level: Scalars['Int']['output'];
  readonly name: Scalars['String']['output'];
  readonly parentCode?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
};

export type RegionCoordinatesPayload = {
  readonly message: Scalars['String']['output'];
  readonly region?: Maybe<Region>;
  readonly success: Scalars['Boolean']['output'];
};

export type RegionHierarchy = {
  readonly cities: ReadonlyArray<Region>;
  readonly city: Region;
  readonly district: Region;
  readonly districts: ReadonlyArray<Region>;
  readonly province: Region;
  readonly provinces: ReadonlyArray<Region>;
};

export type RequestRefundInput = {
  readonly amount: Scalars['BigDecimal']['input'];
  readonly orderId: Scalars['Long']['input'];
  readonly outTradeNo: Scalars['String']['input'];
  readonly reason: Scalars['String']['input'];
};

export type ReverseGeocodePayload = {
  readonly city?: Maybe<Scalars['String']['output']>;
  readonly cityCode?: Maybe<Scalars['String']['output']>;
  readonly confidence?: Maybe<Scalars['Float']['output']>;
  readonly district?: Maybe<Scalars['String']['output']>;
  readonly districtCode?: Maybe<Scalars['String']['output']>;
  readonly formattedAddress?: Maybe<Scalars['String']['output']>;
  readonly message: Scalars['String']['output'];
  readonly province?: Maybe<Scalars['String']['output']>;
  readonly provinceCode?: Maybe<Scalars['String']['output']>;
  readonly street?: Maybe<Scalars['String']['output']>;
  readonly success: Scalars['Boolean']['output'];
};

export type Review = {
  readonly comment?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly deliveryWorkerId: Scalars['Long']['output'];
  readonly deliveryWorkerName?: Maybe<Scalars['String']['output']>;
  readonly isAnonymous: Scalars['Boolean']['output'];
  readonly orderId: Scalars['Long']['output'];
  readonly rating: Scalars['Int']['output'];
  readonly reviewId: Scalars['Long']['output'];
  readonly userId?: Maybe<Scalars['Long']['output']>;
};

export type ServiceAreaPayload = {
  readonly inServiceArea: Scalars['Boolean']['output'];
  readonly message: Scalars['String']['output'];
  readonly success: Scalars['Boolean']['output'];
};

export type SuspiciousTransaction = {
  readonly adminNote?: Maybe<Scalars['String']['output']>;
  readonly amount: Scalars['Money']['output'];
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly frozenAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly frozenBy?: Maybe<Scalars['Long']['output']>;
  readonly id: Scalars['String']['output'];
  readonly isFrozen: Scalars['Boolean']['output'];
  readonly metadata?: Maybe<Scalars['Map']['output']>;
  readonly orderId: Scalars['Long']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly riskScore: Scalars['Float']['output'];
  readonly status: PaymentStatus;
  readonly suspiciousReason: Scalars['String']['output'];
  readonly transactionId?: Maybe<Scalars['String']['output']>;
  readonly userId: Scalars['Long']['output'];
};

export type UpdateAddressInput = {
  readonly city?: InputMaybe<Scalars['String']['input']>;
  readonly cityCode?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress?: InputMaybe<Scalars['String']['input']>;
  readonly district?: InputMaybe<Scalars['String']['input']>;
  readonly districtCode?: InputMaybe<Scalars['String']['input']>;
  readonly isDefault?: InputMaybe<Scalars['Boolean']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly province?: InputMaybe<Scalars['String']['input']>;
  readonly provinceCode?: InputMaybe<Scalars['String']['input']>;
  readonly receiverName?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateDeliveryAddressInput = {
  readonly city?: InputMaybe<Scalars['String']['input']>;
  readonly detailAddress?: InputMaybe<Scalars['String']['input']>;
  readonly district?: InputMaybe<Scalars['String']['input']>;
  readonly latitude?: InputMaybe<Scalars['Float']['input']>;
  readonly longitude?: InputMaybe<Scalars['Float']['input']>;
  readonly province?: InputMaybe<Scalars['String']['input']>;
  readonly receiverName?: InputMaybe<Scalars['String']['input']>;
  readonly receiverPhone?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateDeliveryWorkerInput = {
  readonly avatarUrl?: InputMaybe<Scalars['String']['input']>;
  readonly coordinates?: InputMaybe<Scalars['String']['input']>;
  readonly currentLocation?: InputMaybe<Scalars['String']['input']>;
  readonly earning?: InputMaybe<Scalars['Money']['input']>;
  readonly isAvailable?: InputMaybe<Scalars['Boolean']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
  readonly rating?: InputMaybe<Scalars['BigDecimal']['input']>;
  readonly wechatOpenId?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProductInput = {
  readonly coverImageUrl?: InputMaybe<Scalars['String']['input']>;
  readonly description?: InputMaybe<Scalars['String']['input']>;
  readonly detailImages?: InputMaybe<Scalars['String']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly price?: InputMaybe<Scalars['Money']['input']>;
  readonly stock?: InputMaybe<Scalars['Int']['input']>;
};

export type UpdateProfileInput = {
  readonly avatar?: InputMaybe<Scalars['String']['input']>;
  readonly nickname?: InputMaybe<Scalars['String']['input']>;
  readonly phone?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateRegionInput = {
  readonly name?: InputMaybe<Scalars['String']['input']>;
  readonly parentCode?: InputMaybe<Scalars['String']['input']>;
};

export type UpdateTransactionInput = {
  readonly adminNote?: InputMaybe<Scalars['String']['input']>;
  readonly freezeReason?: InputMaybe<Scalars['String']['input']>;
  readonly isFrozen?: InputMaybe<Scalars['Boolean']['input']>;
  readonly status?: InputMaybe<PaymentStatus>;
};

export type User = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['Long']['output'];
  readonly nickname?: Maybe<Scalars['String']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type UserInfo = {
  readonly avatarUrl?: Maybe<Scalars['String']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly id: Scalars['Long']['output'];
  readonly nickname?: Maybe<Scalars['String']['output']>;
  readonly phone?: Maybe<Scalars['String']['output']>;
  readonly updatedAt: Scalars['LocalDateTime']['output'];
  readonly wechatOpenId: Scalars['String']['output'];
};

export type UserListInput = {
  readonly page?: InputMaybe<Scalars['Int']['input']>;
  readonly search?: InputMaybe<Scalars['String']['input']>;
  readonly size?: InputMaybe<Scalars['Int']['input']>;
  readonly sort?: InputMaybe<Scalars['String']['input']>;
  readonly status?: InputMaybe<UserStatus>;
};

export type UserListResponse = {
  readonly content: ReadonlyArray<User>;
  readonly empty: Scalars['Boolean']['output'];
  readonly first: Scalars['Boolean']['output'];
  readonly last: Scalars['Boolean']['output'];
  readonly number: Scalars['Int']['output'];
  readonly size: Scalars['Int']['output'];
  readonly totalElements: Scalars['Long']['output'];
  readonly totalPages: Scalars['Int']['output'];
};

export type UserPaymentTransaction = {
  readonly amount: Scalars['BigDecimal']['output'];
  readonly completedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly createdAt: Scalars['LocalDateTime']['output'];
  readonly failureReason?: Maybe<Scalars['String']['output']>;
  readonly id: Scalars['String']['output'];
  readonly orderId: Scalars['Long']['output'];
  readonly orderNumber: Scalars['String']['output'];
  readonly paymentMethod: PaymentMethod;
  readonly refundAmount?: Maybe<Scalars['BigDecimal']['output']>;
  readonly refundedAt?: Maybe<Scalars['LocalDateTime']['output']>;
  readonly status: PaymentStatus;
  readonly transactionId?: Maybe<Scalars['String']['output']>;
};

export enum UserRole {
  ADMIN = 'ADMIN',
  NONE = 'NONE',
  USER = 'USER',
  WORKER = 'WORKER'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED'
}

export type ValidateAddressInput = {
  readonly city: Scalars['String']['input'];
  readonly district: Scalars['String']['input'];
  readonly province: Scalars['String']['input'];
};

export type WeChatLoginResponse = {
  readonly accessToken: Scalars['String']['output'];
  readonly expiresIn: Scalars['Int']['output'];
  readonly refreshToken: Scalars['String']['output'];
  readonly userInfo: UserInfo;
};

export type WeChatTokenResponse = {
  readonly accessToken: Scalars['String']['output'];
  readonly expiresIn: Scalars['Int']['output'];
  readonly refreshToken: Scalars['String']['output'];
};

export type WechatCallbackInput = {
  readonly appId?: InputMaybe<Scalars['String']['input']>;
  readonly mchId?: InputMaybe<Scalars['String']['input']>;
  readonly outTradeNo?: InputMaybe<Scalars['String']['input']>;
  readonly resource: Scalars['String']['input'];
  readonly resourceType: Scalars['String']['input'];
  readonly summary: Scalars['String']['input'];
  readonly transactionId?: InputMaybe<Scalars['String']['input']>;
};

export type WechatLoginInput = {
  readonly code: Scalars['String']['input'];
};

export type WeeklyStatistic = {
  readonly endDate: Scalars['String']['output'];
  readonly orderCount: Scalars['Int']['output'];
  readonly revenue: Scalars['Money']['output'];
  readonly startDate: Scalars['String']['output'];
  readonly weekNumber: Scalars['Int']['output'];
  readonly year: Scalars['Int']['output'];
};
