/*
 * AquaRush
 *
 * Copyright (C) 2025 AquaRush Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package dev.yidafu.aqua.order.mapper

import dev.yidafu.aqua.api.dto.CreateOrderRequest
import dev.yidafu.aqua.common.domain.model.DeliveryAddressModel
import dev.yidafu.aqua.common.domain.model.OrderModel
import dev.yidafu.aqua.common.domain.model.OrderStatus
import dev.yidafu.aqua.common.domain.model.PaymentType
import dev.yidafu.aqua.common.graphql.generated.*
import dev.yidafu.aqua.common.id.DefaultIdGenerator
import dev.yidafu.aqua.order.dto.CreateOrderDTO
import dev.yidafu.aqua.order.dto.OrderDTO
import dev.yidafu.aqua.order.dto.UpdateOrderStatusDTO
import org.springframework.stereotype.Component
import tech.mappie.api.EnumMappie
import tech.mappie.api.ObjectMappie
import tools.jackson.module.kotlin.jacksonObjectMapper
import java.time.LocalDateTime
import dev.yidafu.aqua.common.graphql.generated.OrderStatus as OrderStatusG
import dev.yidafu.aqua.common.graphql.generated.PaymentType as PaymentTypeG

// ============================================================================
// OrderModel ↔ OrderDTO Mappers
// ============================================================================

/**
 * Enum mapper for converting domain PaymentType to GraphQL PaymentType
 */
object PaymentTypeMapper : EnumMappie<PaymentType, PaymentTypeG>()

/**
 * Mapper for converting OrderModel to OrderDTO
 */
object OrderModelToDTOMapper : ObjectMappie<OrderModel, OrderDTO>() {
  override fun map(from: OrderModel) = mapping {
    to::id fromProperty from::id
    to::orderNumber fromProperty from::orderNumber
    to::userId fromProperty from::userId
    to::productId fromProperty from::productId
    to::quantity fromProperty from::quantity
    to::amount fromProperty from::amountCents
    to::addressId fromProperty from::addressId
    to::status fromProperty from::status
    to::paymentMethod fromProperty from::paymentMethod
    to::paymentTransactionId fromProperty from::paymentTransactionId
    to::paymentTime fromProperty from::paymentTime
    to::deliveryWorkerId fromProperty from::deliveryWorkerId
    to::deliveryPhotos fromExpression {
      from.deliveryPhotos?.let { photos ->
        try {
          jacksonObjectMapper().readValue(photos, Array<String>::class.java).toList()
        } catch (e: Exception) {
          emptyList()
        }
      }
    }
    to::deliveryAddressId fromProperty from::deliveryAddressId
    to::completedAt fromProperty from::completedAt
    to::totalAmount fromProperty from::amountCents
    to::createdAt fromProperty from::createdAt
    to::updatedAt fromProperty from::updatedAt
    // Nested objects are set to null and should be populated by the service layer
    to::user fromValue null
    to::product fromValue null
    to::address fromValue null
    to::deliveryWorker fromValue null
    to::deliveryStartedAt fromProperty from::deliveryStartedAt
    to::deliveryConfirmedAt fromProperty from::deliveryConfirmedAt
    to::isSelfCollect fromProperty from::isSelfCollect
    to::paymentType fromProperty from::paymentType
  }
}

/**
 * Mapper for converting CreateOrderDTO to OrderModel
 */
object CreateOrderDTOToModelMapper : ObjectMappie<CreateOrderDTO, OrderModel>() {
  override fun map(from: CreateOrderDTO) = mapping {
    to::id fromValue -1L // Will be generated by database
    to::orderNumber fromValue "" // This should be generated by the service
    to::userId fromProperty from::userId
    to::productId fromProperty from::productId
    to::quantity fromProperty from::quantity
    to::amountCents fromProperty from::amount
    to::addressId fromProperty from::addressId
    to::deliveryAddressId fromProperty from::deliveryAddressId
    to::status fromExpression { OrderStatus.PENDING_PAYMENT }
    to::paymentMethod fromProperty from::paymentMethod
    to::deliveryPhotos fromValue null
    to::paymentTransactionId fromValue null
    to::paymentTime fromValue null
    to::deliveryWorkerId fromValue null
    to::completedAt fromValue null
    to::createdAt fromValue LocalDateTime.now()
    to::updatedAt fromValue LocalDateTime.now()
    to::deliveryStartedAt fromValue null
    to::deliveryConfirmedAt fromValue null
    to::isSelfCollect fromValue false
    to::paymentType fromValue null
  }
}

/**
 * Mapper for applying UpdateOrderStatusDTO to OrderModel
 */
object UpdateOrderStatusMapper : ObjectMappie<UpdateOrderStatusDTO, OrderModel>() {
  override fun map(from: UpdateOrderStatusDTO) = mapping {
    to::id fromValue -1L // This needs to be set by the calling code
    to::orderNumber fromValue "" // This needs to be set by the calling code
    to::userId fromValue -1L // This needs to be set by the calling code
    to::productId fromValue -1L // This needs to be set by the calling code
    to::quantity fromValue 1 // This needs to be set by the calling code
    to::amountCents fromValue 0L // This needs to be set by the calling code
    to::addressId fromValue -1L // This needs to be set by the calling code
    to::deliveryAddressId fromValue -1L // This needs to be set by the calling code
    to::status fromExpression { from.status }
    to::paymentMethod fromProperty from::paymentMethod
    to::deliveryPhotos fromExpression {
      from.deliveryPhotos?.let { photos ->
        jacksonObjectMapper().writeValueAsString(photos)
      }
    }
    to::paymentTransactionId fromProperty from::paymentTransactionId
    to::paymentTime fromProperty from::paymentTime
    to::deliveryWorkerId fromProperty from::deliveryWorkerId
    to::completedAt fromProperty from::completedAt
    to::createdAt fromValue LocalDateTime.now()
    to::updatedAt fromValue LocalDateTime.now()
    to::deliveryStartedAt fromValue null
    to::deliveryConfirmedAt fromValue null
    to::isSelfCollect fromValue false
    to::paymentType fromValue null
  }
}

// ============================================================================
// OrderDTO ↔ GraphQL Order Mappers
// ============================================================================

/**
 * Mapper for converting OrderDTO to GraphQL Order type
 */
object OrderDTOToGraphQLMapper : ObjectMappie<OrderDTO, Order>() {
  override fun map(from: OrderDTO) = mapping {
    // Note: GraphQL Order requires non-null nested objects (address, product, user)
    // This mapper should only be used when nested objects are properly populated
    to::id fromProperty from::id
    to::orderNumber fromProperty from::orderNumber
    to::amount fromProperty from::amount
    to::completedAt fromProperty from::completedAt
    to::createdAt fromProperty from::createdAt
    to::deliveryPhotos fromExpression { from.deliveryPhotos }
    to::paymentMethod fromExpression { from.paymentMethod?.name }
    to::paymentTime fromProperty from::paymentTime
    to::paymentTransactionId fromProperty from::paymentTransactionId
    to::quantity fromProperty from::quantity
    to::status fromExpression { OrderStatusG.valueOf(from.status.name) }
    to::updatedAt fromProperty from::updatedAt
    // These are required by GraphQL Order constructor - use requireNotNull
    to::address fromExpression { requireNotNull(from.address) { "address must not be null" } }
    to::deliveryWorker fromProperty from::deliveryWorker
    to::product fromExpression { requireNotNull(from.product) { "product must not be null" } }
    to::user fromExpression { requireNotNull(from.user) { "user must not be null" } }
    // Added missing fields
    to::deliveryConfirmedAt fromProperty from::deliveryConfirmedAt
    to::deliveryStartedAt fromProperty from::deliveryStartedAt
    to::isSelfCollect fromProperty from::isSelfCollect
    to::paymentType fromProperty from::paymentType
  }
}

/**
 * Mapper for converting GraphQL Order type to OrderDTO
 */
object GraphQLToOrderDTOMapper : ObjectMappie<Order, OrderDTO>() {
  override fun map(from: Order) = mapping {
    to::id fromProperty from::id
    to::orderNumber fromProperty from::orderNumber
    to::userId fromExpression { from.user.id }
    to::user fromValue from.user
    to::productId fromExpression { from.product.id }
    to::product fromValue from.product
    to::quantity fromProperty from::quantity
    to::amount fromProperty from::amount
    to::addressId fromExpression { from.address.id }
    to::address fromValue from.address
    to::status fromExpression {
      when (from.status.name) {
        "PENDING_PAYMENT" -> OrderStatus.PENDING_PAYMENT
        "PENDING_DELIVERY" -> OrderStatus.PENDING_DELIVERY
        "DELIVERING" -> OrderStatus.DELIVERING
        "COMPLETED" -> OrderStatus.COMPLETED
        "CANCELLED" -> OrderStatus.CANCELLED
        else -> OrderStatus.PENDING_PAYMENT
      }
    }
    to::paymentMethod fromExpression {
      when (from.paymentMethod) {
        "WECHAT_PAY" -> dev.yidafu.aqua.common.domain.model.PaymentMethod.WECHAT_PAY
        else -> null
      }
    }
    to::paymentTransactionId fromProperty from::paymentTransactionId
    to::paymentTime fromProperty from::paymentTime
    to::deliveryWorkerId fromExpression { from.deliveryWorker?.id }
    to::deliveryWorker fromProperty from::deliveryWorker
    to::deliveryPhotos fromExpression { from.deliveryPhotos?.toList() }
    to::deliveryAddressId fromExpression { from.address.id }
    to::completedAt fromProperty from::completedAt
    to::totalAmount fromProperty from::amount
    to::createdAt fromProperty from::createdAt
    to::updatedAt fromProperty from::updatedAt
    to::deliveryStartedAt fromProperty from::deliveryStartedAt
    to::deliveryConfirmedAt fromProperty from::deliveryConfirmedAt
    to::isSelfCollect fromProperty from::isSelfCollect
    to::paymentType fromProperty from::paymentType
  }
}

// ============================================================================
// OrderModel → GraphQL Order Direct Mapper (with placeholders)
// ============================================================================

/**
 * Simple OrderMapper that converts OrderModel to GraphQL Order
 * Note: This mapper creates placeholder objects for required nested fields
 * In a complete implementation, these should be loaded from their respective services
 */
object OrderMapper : ObjectMappie<OrderModel, Order>() {
  override fun map(from: OrderModel) = mapping {
    // Create placeholder objects for required nested fields
    // In a real implementation, these should be loaded from their respective services
    to::id fromProperty from::id
    to::orderNumber fromProperty from::orderNumber
    to::amount fromProperty from::amountCents
    to::completedAt fromProperty from::completedAt
    to::createdAt fromProperty from::createdAt
    to::deliveryPhotos fromExpression {
      from.deliveryPhotos?.let { photos ->
        try {
          jacksonObjectMapper().readValue(photos, Array<String>::class.java).toList()
        } catch (e: Exception) {
          emptyList()
        }
      }
    }
    to::paymentMethod fromExpression { from.paymentMethod?.name }
    to::paymentTime fromProperty from::paymentTime
    to::paymentTransactionId fromProperty from::paymentTransactionId
    to::quantity fromProperty from::quantity
    to::status fromExpression {
      when (from.status.name) {
        "PENDING_PAYMENT" -> OrderStatusG.PENDING
        "PENDING_DELIVERY" -> OrderStatusG.PENDING
        "DELIVERING" -> OrderStatusG.OUT_FOR_DELIVERY
        "COMPLETED" -> OrderStatusG.DELIVERED
        "CANCELLED" -> OrderStatusG.CANCELLED
        else -> OrderStatusG.PENDING
      }
    }
    to::updatedAt fromProperty from::updatedAt
    to::address fromExpression {
      Address(
        id = from.addressId,
        userId = from.userId,
        province = "placeholder",
        provinceCode = null,
        city = "placeholder",
        cityCode = null,
        district = "placeholder",
        districtCode = null,
        detailAddress = "placeholder",
        isDefault = false,
        latitude = null,
        longitude = null,
        phone = "",
        receiverName = "",
        createdAt = from.createdAt,
        updatedAt = from.updatedAt,
      )
    }
    to::deliveryWorker fromValue null // Optional field
    to::product fromExpression {
      Product(
        id = from.productId,
        name = "placeholder",
        coverImageUrl = "",
        price = from.amountCents,
        stock = 1,
        status = ProductStatus.ONLINE,
        createdAt = from.createdAt,
        updatedAt = from.updatedAt,
        certificateImages = null,
        deliverySettings = null,
        depositPrice = null,
        detailContent = null,
        imageGallery = null,
        isDeleted = false,
        mineralContent = null,
        originalPrice = null,
        salesVolume = 0,
        sortOrder = 0,
        specification = "",
        subtitle = null,
        tags = null,
        waterSource = null,
      )
    }
    to::user fromExpression {
      User(
        id = from.userId,
        nickname = "placeholder",
        phone = "placeholder",
        wechatOpenId = "placeholder_openid",
        avatarUrl = null,
        createdAt = from.createdAt,
        updatedAt = from.updatedAt,
        balanceCents = 0L,
        email = "",
        role = UserRole.USER,
        status = UserStatus.ACTIVE,
        totalSpentCents = 0L,
      )
    }
    // Added missing fields
    to::deliveryConfirmedAt fromProperty from::deliveryConfirmedAt
    to::deliveryStartedAt fromProperty from::deliveryStartedAt
    to::isSelfCollect fromProperty from::isSelfCollect
    to::paymentType fromExpression { from.paymentType?.let { PaymentTypeMapper.map(it) } }
  }
}

/**
 * Mapper for converting DeliveryAddressModel domain entity to GraphQL DeliveryAddress type
 */
object DeliveryAddressMapper : ObjectMappie<DeliveryAddressModel, DeliveryAddress>() {
  override fun map(from: DeliveryAddressModel) =
    mapping {
      to::latitude fromValue from.latitude?.toFloat()
      to::longitude fromValue from.longitude?.toFloat()
      // Most fields map automatically by name
      // Note: Mappie automatically handles Double to Float conversion for nullable fields
    }
}

/**
 * CreateOrderRequest 到 Order 的映射器
 */
@Component
object CreateOrderRequestMapper : ObjectMappie<CreateOrderRequest, OrderModel>() {
  override fun map(from: CreateOrderRequest) = mapping {
    to::id fromValue DefaultIdGenerator().generate()
    to::orderNumber fromProperty from::orderNumber
    to::userId fromProperty from::userId
    to::productId fromProperty from::productId
    to::quantity fromProperty from::quantity
    to::amountCents fromProperty from::amount
    to::addressId fromProperty from::addressId
    to::deliveryAddressId fromProperty from::addressId
    to::status fromValue OrderStatus.PENDING_PAYMENT
    to::paymentMethod fromValue null
    to::paymentTransactionId fromValue null
    to::paymentTime fromValue null
    to::deliveryWorkerId fromValue null
    to::deliveryPhotos fromValue null
    to::completedAt fromValue null
    to::createdAt fromValue LocalDateTime.now()
    to::updatedAt fromValue LocalDateTime.now()
    to::deliveryStartedAt fromValue null
    to::deliveryConfirmedAt fromValue null
    to::isSelfCollect fromValue false
    to::paymentType fromValue null
  }
}
