/*
 * AquaRush
 *
 * Copyright (C) 2025 AquaRush Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package dev.yidafu.aqua.order.mapper

import dev.yidafu.aqua.api.dto.CreateOrderRequest
import dev.yidafu.aqua.common.domain.model.DeliveryAddressModel
import dev.yidafu.aqua.common.domain.model.OrderModel
import dev.yidafu.aqua.common.domain.model.OrderStatus
import dev.yidafu.aqua.common.domain.model.PaymentType
import dev.yidafu.aqua.common.graphql.generated.DeliveryAddress
import dev.yidafu.aqua.common.graphql.generated.Order
import dev.yidafu.aqua.common.id.DefaultIdGenerator
import dev.yidafu.aqua.delivery.mapper.DeliveryWorkerMapper
import dev.yidafu.aqua.order.dto.CreateOrderDTO
import dev.yidafu.aqua.order.dto.OrderDTO
import dev.yidafu.aqua.order.dto.UpdateOrderStatusDTO
import dev.yidafu.aqua.product.mapper.ProductMapper
import dev.yidafu.aqua.user.mapper.AddressMapper
import dev.yidafu.aqua.user.mapper.UserMapper
import org.springframework.stereotype.Component
import tech.mappie.api.EnumMappie
import tech.mappie.api.ObjectMappie
import tools.jackson.module.kotlin.jacksonObjectMapper
import java.time.LocalDateTime
import dev.yidafu.aqua.common.graphql.generated.OrderStatus as OrderStatusG
import dev.yidafu.aqua.common.graphql.generated.PaymentType as PaymentTypeG

// ============================================================================
// OrderModel ↔ OrderDTO Mappers
// ============================================================================

/**
 * Enum mapper for converting domain PaymentType to GraphQL PaymentType
 */
object PaymentTypeMapper : EnumMappie<PaymentType, PaymentTypeG>()

/**
 * Mapper for converting OrderModel to OrderDTO
 */
object OrderModelToDTOMapper : ObjectMappie<OrderModel, OrderDTO>() {
  override fun map(from: OrderModel) =
    mapping {
      // Fields with same name and type - auto-mapped by Mappie
      to::amount fromProperty from::amountCents
      to::deliveryPhotos fromExpression {
        from.deliveryPhotos?.let { photos ->
          try {
            jacksonObjectMapper().readValue(photos, Array<String>::class.java).toList()
          } catch (e: Exception) {
            emptyList()
          }
        }
      }
      to::totalAmount fromProperty from::amountCents
      // Nested objects are set to null and should be populated by the service layer
      to::user fromValue null
      to::product fromValue null
      to::address fromValue null
      to::deliveryWorker fromValue null
    }
}

/**
 * Mapper for converting CreateOrderDTO to OrderModel
 */
object CreateOrderDTOToModelMapper : ObjectMappie<CreateOrderDTO, OrderModel>() {
  override fun map(from: CreateOrderDTO) =
    mapping {
      to::id fromValue -1L // Will be generated by database
      to::orderNumber fromValue "" // This should be generated by the service
      // Fields with same name and type - auto-mapped by Mappie
      to::amountCents fromProperty from::amount
      to::status fromExpression { OrderStatus.PENDING_PAYMENT }
      to::deliveryPhotos fromValue null
      to::paymentTransactionId fromValue null
      to::paymentTime fromValue null
      to::deliveryWorkerId fromValue null
      to::completedAt fromValue null
      to::createdAt fromValue LocalDateTime.now()
      to::updatedAt fromValue LocalDateTime.now()
      to::deliveryStartedAt fromValue null
      to::deliveryConfirmedAt fromValue null
      to::isSelfCollect fromValue false
      to::paymentType fromValue null
    }
}

/**
 * Mapper for applying UpdateOrderStatusDTO to OrderModel
 */
object UpdateOrderStatusMapper : ObjectMappie<UpdateOrderStatusDTO, OrderModel>() {
  override fun map(from: UpdateOrderStatusDTO) =
    mapping {
      to::id fromValue -1L // This needs to be set by the calling code
      to::orderNumber fromValue "" // This needs to be set by the calling code
      to::userId fromValue -1L // This needs to be set by the calling code
      to::productId fromValue -1L // This needs to be set by the calling code
      to::quantity fromValue 1 // This needs to be set by the calling code
      to::amountCents fromValue 0L // This needs to be set by the calling code
      to::addressId fromValue -1L // This needs to be set by the calling code
      to::status fromExpression { from.status }
      to::deliveryPhotos fromExpression {
        from.deliveryPhotos?.let { photos ->
          jacksonObjectMapper().writeValueAsString(photos)
        }
      }
      to::createdAt fromValue LocalDateTime.now()
      to::updatedAt fromValue LocalDateTime.now()
      to::deliveryStartedAt fromValue null
      to::deliveryConfirmedAt fromValue null
      to::isSelfCollect fromValue false
      to::paymentType fromValue null
    }
}

// ============================================================================
// OrderDTO ↔ GraphQL Order Mappers
// ============================================================================

/**
 * Mapper for converting OrderDTO to GraphQL Order type
 */
object OrderDTOToGraphQLMapper : ObjectMappie<OrderDTO, Order>() {
  override fun map(from: OrderDTO) =
    mapping {
      // Note: GraphQL Order requires non-null nested objects (address, product, user)
      // This mapper should only be used when nested objects are properly populated
      to::amount fromProperty from::amount
      to::deliveryPhotos fromExpression { from.deliveryPhotos }
      to::paymentMethod fromExpression { from.paymentMethod?.name }
      to::status fromExpression { OrderStatusG.valueOf(from.status.name) }
      // These are required by GraphQL Order constructor - use requireNotNull
      to::address fromExpression { requireNotNull(from.address) { "address must not be null" } }
      to::product fromExpression { requireNotNull(from.product) { "product must not be null" } }
      to::user fromExpression { requireNotNull(from.user) { "user must not be null" } }
    }
}

/**
 * Mapper for converting GraphQL Order type to OrderDTO
 */
object GraphQLToOrderDTOMapper : ObjectMappie<Order, OrderDTO>() {
  override fun map(from: Order) =
    mapping {
      to::userId fromExpression { from.user?.id ?: 0L }
      to::user fromValue from.user
      to::productId fromExpression { from.product?.id ?: 0L }
      to::product fromValue from.product
      to::amount fromProperty from::amount
      to::addressId fromExpression { from.address?.id ?: 0L }
      to::address fromValue from.address
      to::status fromExpression {
        GenerateOrderStatusMapper.map(from.status)
      }
      to::paymentMethod fromExpression {
        when (from.paymentMethod) {
          "WECHAT_PAY" -> dev.yidafu.aqua.common.domain.model.PaymentMethod.WECHAT_PAY
          else -> null
        }
      }
      to::deliveryWorkerId fromExpression { from.deliveryWorker?.id }
      to::deliveryWorker fromValue from.deliveryWorker
      to::deliveryPhotos fromExpression { from.deliveryPhotos?.toList() }
      to::totalAmount fromProperty from::amount
    }
}

// ============================================================================
// OrderModel → GraphQL Order Direct Mapper (with placeholders)
// ============================================================================
object OrderStatusMapper : EnumMappie<OrderStatus, OrderStatusG>()

object GenerateOrderStatusMapper : EnumMappie<OrderStatusG, OrderStatus>()

/**
 * Simple OrderMapper that converts OrderModel to GraphQL Order
 * Note: This mapper creates placeholder objects for required nested fields
 * In a complete implementation, these should be loaded from their respective services
 */
object OrderMapper : ObjectMappie<OrderModel, Order>() {
  override fun map(from: OrderModel) =
    mapping {
      // Create placeholder objects for required nested fields
      // In a real implementation, these should be loaded from their respective services
      to::amount fromProperty from::amountCents
      to::deliveryPhotos fromExpression {
        from.deliveryPhotos?.let { photos ->
          try {
            jacksonObjectMapper().readValue(photos, Array<String>::class.java).toList()
          } catch (e: Exception) {
            emptyList()
          }
        }
      }
      to::paymentMethod fromExpression { from.paymentMethod?.name }
      to::status fromExpression {
        OrderStatusMapper.map(from.status)
      }
      // Create placeholder objects for required nested fields
      to::address fromExpression { from.address?.let { AddressMapper.map(it) } }

      to::deliveryWorker fromExpression { from.deliveryWorker?.let { DeliveryWorkerMapper.map(it) } }
      to::product fromExpression {
        from.product?.let {
          ProductMapper.map(it)
        }
      }
      to::user fromExpression {
        from.user?.let { UserMapper.map(it) }
      }
      to::paymentType fromExpression { from.paymentType?.let { PaymentTypeMapper.map(it) } }
    }
}

/**
 * Mapper for converting DeliveryAddressModel domain entity to GraphQL DeliveryAddress type
 */
object DeliveryAddressMapper : ObjectMappie<DeliveryAddressModel, DeliveryAddress>() {
  override fun map(from: DeliveryAddressModel) =
    mapping {
      to::latitude fromValue from.latitude?.toFloat()
      to::longitude fromValue from.longitude?.toFloat()
      // Most fields map automatically by name
      // Note: Mappie automatically handles Double to Float conversion for nullable fields
    }
}

/**
 * CreateOrderRequest 到 Order 的映射器
 */
@Component
object CreateOrderRequestMapper : ObjectMappie<CreateOrderRequest, OrderModel>() {
  override fun map(from: CreateOrderRequest) =
    mapping {
      to::id fromValue DefaultIdGenerator().generate()
      // Fields with same name and type - auto-mapped by Mappie
      to::amountCents fromProperty from::amount
      to::status fromValue OrderStatus.PENDING_PAYMENT
      to::paymentMethod fromValue null
      to::paymentTransactionId fromValue null
      to::paymentTime fromValue null
      to::deliveryWorkerId fromValue null
      to::deliveryPhotos fromValue null
      to::completedAt fromValue null
      to::createdAt fromValue LocalDateTime.now()
      to::updatedAt fromValue LocalDateTime.now()
      to::deliveryStartedAt fromValue null
      to::deliveryConfirmedAt fromValue null
      to::isSelfCollect fromValue false
      to::paymentType fromValue null
    }
}
