#!/usr/bin/env python3
import json
import os

def generate_sql():
    """Generate SQL INSERT statements for regions table from pca-code.json"""

    # Read the JSON data
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_file = os.path.join(script_dir, 'pca-code.json')
    sql_file = os.path.join(script_dir, '../modules/aqua-entry/src/main/resources/db/changelog/changes/insert-regions.sql')

    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    sql_statements = []
    sql_statements.append("-- Insert regions data from pca-code.json")
    sql_statements.append("-- Generated by generate-regions-sql.py")
    sql_statements.append("")

    # Helper function to process regions recursively
    def process_region(region, parent_code=None, level=1):
        code = region['code']
        name = region['name']

        # Escape single quotes in names for SQL
        escaped_name = name.replace("'", "''")

        # Generate INSERT statement
        sql = f"INSERT INTO regions (name, code, parent_code, level) VALUES ('{escaped_name}', '{code}'"
        if parent_code:
            sql += f", '{parent_code}'"
        else:
            sql += ", '0'"
        sql += f", {level});"
        sql_statements.append(sql)

        # Process children if they exist
        if 'children' in region:
            for child in region['children']:
                process_region(child, code, level + 1)

    # Process all top-level regions (provinces/municipalities)
    for province in data:
        process_region(province, None, 1)

    # Write SQL statements to file
    with open(sql_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_statements))

    print(f"Generated {len([s for s in sql_statements if s.startswith('INSERT')])} INSERT statements")
    print(f"SQL file saved to: {sql_file}")

if __name__ == "__main__":
    generate_sql()
